/*
 * 
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 * Copyright 2002-2008, Thomas Kellerer
 * 
 * No part of this code maybe reused without the permission of the author
 * 
 * To contact the author please send an email to: support@sql-workbench.net
 * 
 */
package workbench.gui.macros;

import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.beans.PropertyChangeListener;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import workbench.gui.components.BooleanPropertyEditor;
import workbench.gui.components.StringPropertyEditor;
import workbench.gui.components.WbTraversalPolicy;
import workbench.gui.sql.EditorPanel;
import workbench.resource.ResourceMgr;
import workbench.sql.macros.MacroDefinition;

/**
 *
 * @author support@sql-workbench.net
 */
public class MacroDefinitionPanel
	extends javax.swing.JPanel
{
	private EditorPanel macroEditor;
	private MacroDefinition currentMacro;
	
	public MacroDefinitionPanel(PropertyChangeListener l)
	{
		initComponents();
		macroEditor = EditorPanel.createSqlEditor();
		macroEditor.showFindOnPopupMenu();
		macroEditor.showFormatSql();
		GridBagConstraints c = new GridBagConstraints();
		c.gridx = 0;
		c.gridy = 2;
		c.gridwidth = GridBagConstraints.REMAINDER;
    c.gridwidth = GridBagConstraints.REMAINDER;
    c.fill = GridBagConstraints.BOTH;
		c.weightx = 1.0;
		c.weighty = 1.0;
		c.insets = new Insets(10, 2, 2, 5);
		add(macroEditor, c);

		WbTraversalPolicy policy = new WbTraversalPolicy();
		policy.addComponent(jTextField1);
		policy.addComponent(jCheckBox1);
		policy.addComponent(macroEditor);
		policy.setDefaultComponent(macroEditor);
		setFocusTraversalPolicy(policy);

		jTextField1.addPropertyChangeListener(l);
	}

	public void setMacro(MacroDefinition macro)
	{
		if (currentMacro != null && macroEditor.isModified())
		{
			currentMacro.setText(macroEditor.getText());
		}
		currentMacro = macro;
		
		BooleanPropertyEditor menu = (BooleanPropertyEditor)jCheckBox1;
		menu.setSourceObject(macro, "visibleInMenu");
		menu.setImmediateUpdate(true);

		StringPropertyEditor name = (StringPropertyEditor)jTextField1;
		name.setSourceObject(macro, "name");
		name.setImmediateUpdate(true);

		if (macro != null)
		{
			macroEditor.setText(macro.getText());
			macroEditor.setCaretPosition(0);
		}
		else
		{
			macroEditor.setText("");
		}
	}

	public void selectMacroName()
	{
		EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				jTextField1.requestFocusInWindow();
			}
		});
	}

	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
		GridBagConstraints gridBagConstraints;

    jLabel1 = new JLabel();
    jTextField1 = new StringPropertyEditor();
    jCheckBox1 = new BooleanPropertyEditor();

    setLayout(new GridBagLayout());

    jLabel1.setText(ResourceMgr.getString("LblMacroName")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(8, 5, 0, 0);
    add(jLabel1, gridBagConstraints);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(5, 4, 0, 5);
    add(jTextField1, gridBagConstraints);

    jCheckBox1.setText(ResourceMgr.getString("LblMacroGrpMenu")); // NOI18N
    jCheckBox1.setBorder(null);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    gridBagConstraints.insets = new Insets(6, 5, 0, 5);
    add(jCheckBox1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JCheckBox jCheckBox1;
  private JLabel jLabel1;
  private JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
