CREATE USER WBJUNIT IDENITIFED BY WBJUNIT;

GRANT CREATE SESSION TO WBJUNIT;
GRANT CREATE TABLE TO WBJUNIT;
GRANT CREATE CLUSTER TO WBJUNIT;
GRANT CREATE SYNONYM TO WBJUNIT;
GRANT CREATE VIEW TO WBJUNIT;
GRANT CREATE SEQUENCE TO WBJUNIT;
GRANT CREATE PROCEDURE TO WBJUNIT;
GRANT CREATE TRIGGER TO WBJUNIT;
GRANT CREATE MATERIALIZED VIEW TO WBJUNIT;
GRANT CREATE TYPE TO WBJUNIT;
grant plustrace to wbjunit;

GRANT SELECT ON SYS.V_$SESSION TO WBJUNIT;
GRANT SELECT ON SYS.V_$SQL TO WBJUNIT;
GRANT SELECT ON SYS.V_$SQLAREA TO WBJUNIT;
GRANT SELECT ON SYS.V_$SQL_PLAN TO WBJUNIT;
GRANT SELECT ON SYS.V_$SQL_PLAN_STATISTICS TO WBJUNIT;
GRANT SELECT ON SYS.V_$SQL_PLAN_STATISTICS_ALL TO WBJUNIT;
GRANT SELECT ON SYS.V_$SQL_WORKAREA TO WBJUNIT;
GRANT SELECT ON SYS.V_$TRANSACTION TO WBJUNIT;
GRANT SELECT ON SYS.V_$PARAMETER TO WBJUNIT;

