/*
 * GeneralExportOptionsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2016, Thomas Kellerer
 *
 * Licensed under a modified Apache License, Version 2.0
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at.
 *
 *     http://sql-workbench.net/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.dialogs.export;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import workbench.resource.ResourceMgr;
import workbench.resource.Settings;

import workbench.gui.components.EncodingPanel;
import workbench.gui.components.FlatButton;

import workbench.util.StringUtil;

/**
 *
 * @author  Thomas Kellerer
 */
public class GeneralExportOptionsPanel
	extends JPanel
	implements ExportOptions
{

	public GeneralExportOptionsPanel()
	{
		super();
		initComponents();
	}

	public void saveSettings()
	{
		Settings s = Settings.getInstance();
		s.setProperty("workbench.export.general.dateformat", this.getDateFormat());
		s.setProperty("workbench.export.general.timestampformat", this.getTimestampFormat());
		s.setProperty("workbench.export.general.encoding", this.getEncoding());
		s.setExportNullString(this.getNullString());
	}

	public void restoreSettings()
	{
		Settings s = Settings.getInstance();
		this.setDateFormat(s.getProperty("workbench.export.general.dateformat", ""));
		this.setTimestampFormat(s.getProperty("workbench.export.general.timestampformat", ""));
		this.setEncoding(s.getProperty("workbench.export.general.encoding", s.getDefaultDataEncoding()));
		this.setNullString(s.getExportNullString());
	}

	@Override
	public void setNullString(String value)
	{
		nullString.setText(value);
	}

	@Override
	public String getNullString()
	{
		if (StringUtil.isBlank(nullString.getText()))
		{
			return null;
		}
		return nullString.getText().trim();
	}

	@Override
	public String getDateFormat()
	{
		return this.dateFormat.getText();
	}

	@Override
	public String getEncoding()
	{
		return encodingPanel.getEncoding();
	}

	@Override
	public String getTimestampFormat()
	{
		return this.timestampFormat.getText();
	}

	@Override
	public void setDateFormat(String format)
	{
		dateFormat.setText(format);
	}

	@Override
	public void setEncoding(String enc)
	{
		encodingPanel.setEncoding(enc);
	}

	@Override
	public void setTimestampFormat(String format)
	{
		timestampFormat.setText(format);
	}

	public void showRetrieveColumnsLabel()
	{
		selectColumnsButton.setText(ResourceMgr.getString("LblRetrieveColumns"));
	}

	public void showSelectColumnsLabel()
	{
		selectColumnsButton.setText(ResourceMgr.getString("LblSelectColumns"));
	}
	public void allowSelectColumns(boolean flag)
	{
		this.selectColumnsButton.setEnabled(flag);
	}

	public Object addColumnSelectListener(ActionListener l)
	{
		this.selectColumnsButton.addActionListener(l);
		return this.selectColumnsButton;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    GridBagConstraints gridBagConstraints;

    encodingPanel = new EncodingPanel();
    dateFormatLabel = new JLabel();
    dateFormat = new JTextField();
    timestampFormatLabel = new JLabel();
    timestampFormat = new JTextField();
    selectColumnsButton = new FlatButton();
    nullStringLabel = new JLabel();
    nullString = new JTextField();

    setLayout(new GridBagLayout());
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(0, 5, 0, 4);
    add(encodingPanel, gridBagConstraints);

    dateFormatLabel.setText(ResourceMgr.getString("LblDateFormat")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(8, 6, 0, 0);
    add(dateFormatLabel, gridBagConstraints);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(4, 4, 0, 4);
    add(dateFormat, gridBagConstraints);

    timestampFormatLabel.setText(ResourceMgr.getString("LblTimestampFormat")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(4, 6, 0, 0);
    add(timestampFormatLabel, gridBagConstraints);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(0, 4, 0, 4);
    add(timestampFormat, gridBagConstraints);

    selectColumnsButton.setText(ResourceMgr.getString("LblSelectColumns")); // NOI18N
    selectColumnsButton.setToolTipText(ResourceMgr.getString("d_LblSelectColumns")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new Insets(6, 4, 5, 4);
    add(selectColumnsButton, gridBagConstraints);

    nullStringLabel.setText(ResourceMgr.getString("LblNullString")); // NOI18N
    nullStringLabel.setToolTipText(ResourceMgr.getString("d_LblNullString")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(4, 6, 0, 0);
    add(nullStringLabel, gridBagConstraints);

    nullString.setToolTipText(ResourceMgr.getString("d_LblNullString")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new Insets(0, 4, 0, 4);
    add(nullString, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JTextField dateFormat;
  private JLabel dateFormatLabel;
  private EncodingPanel encodingPanel;
  private JTextField nullString;
  private JLabel nullStringLabel;
  private JButton selectColumnsButton;
  private JTextField timestampFormat;
  private JLabel timestampFormatLabel;
  // End of variables declaration//GEN-END:variables

}
