/*
 * GeneralExportOptionsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2006, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.dialogs.export;

import java.awt.event.ActionListener;
import workbench.resource.ResourceMgr;
import workbench.resource.Settings;

/**
 *
 * @author  support@sql-workbench.net
 */
public class GeneralExportOptionsPanel 
	extends javax.swing.JPanel
	implements ExportOptions
{
	
	/** Creates new form GeneralExportOptionsPanel */
	public GeneralExportOptionsPanel()
	{
		initComponents();
	}

	public void saveSettings()
	{
		Settings s = Settings.getInstance();
		s.setProperty("workbench.export.general.dateformat", this.getDateFormat());
		s.setProperty("workbench.export.general.timestampformat", this.getTimestampFormat());
		s.setProperty("workbench.export.general.encoding", this.getEncoding());
	}
	
	public void restoreSettings()
	{
		Settings s = Settings.getInstance();
		this.setDateFormat(s.getProperty("workbench.export.general.dateformat", ""));
		this.setTimestampFormat(s.getProperty("workbench.export.general.timestampformat", ""));
		this.setEncoding(s.getProperty("workbench.export.general.encoding", s.getDefaultDataEncoding()));
	}
	
	public String getDateFormat()
	{
		return this.dateFormat.getText();
	}

	public String getEncoding()
	{
		return encodingPanel.getEncoding();
	}

	public String getTimestampFormat()
	{
		return this.timestampFormat.getText();
	}

	public void setDateFormat(String format)
	{
		dateFormat.setText(format);
	}

	public void setEncoding(String enc)
	{
		encodingPanel.setEncoding(enc);
	}

	public void setTimestampFormat(String format)
	{
		timestampFormat.setText(format);
	}
	
	public void allowSelectColumns(boolean flag)
	{
		this.selectColumnsButton.setVisible(flag);
	}
	
	public Object addColumnSelectListener(ActionListener l)
	{
		this.selectColumnsButton.addActionListener(l);
		return this.selectColumnsButton;
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  private void initComponents()//GEN-BEGIN:initComponents
  {
    java.awt.GridBagConstraints gridBagConstraints;

    encodingPanel = new workbench.gui.components.EncodingPanel();
    dateFormatLabel = new javax.swing.JLabel();
    dateFormat = new javax.swing.JTextField();
    timestampFormatLabel = new javax.swing.JLabel();
    timestampFormat = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    selectColumnsButton = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    add(encodingPanel, gridBagConstraints);

    dateFormatLabel.setText(ResourceMgr.getString("LabelDateFormat"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
    add(dateFormatLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
    add(dateFormat, gridBagConstraints);

    timestampFormatLabel.setText(ResourceMgr.getString("LabelTimestampFormat"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
    add(timestampFormatLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
    add(timestampFormat, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jPanel1, gridBagConstraints);

    selectColumnsButton.setText(ResourceMgr.getString("LabelSelectColumns"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
    add(selectColumnsButton, gridBagConstraints);

  }//GEN-END:initComponents
	
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField dateFormat;
  private javax.swing.JLabel dateFormatLabel;
  private workbench.gui.components.EncodingPanel encodingPanel;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton selectColumnsButton;
  private javax.swing.JTextField timestampFormat;
  private javax.swing.JLabel timestampFormatLabel;
  // End of variables declaration//GEN-END:variables
	
}
