/*
 * XmlOptionsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2008, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.dialogs.export;

import workbench.resource.ResourceMgr;
import workbench.resource.Settings;

/**
 *
 * @author  support@sql-workbench.net
 */
public class XmlOptionsPanel
	extends javax.swing.JPanel
	implements XmlOptions
{

	public XmlOptionsPanel()
	{
		super();
		initComponents();
	}

	public void saveSettings()
	{
		Settings s = Settings.getInstance();
		s.setProperty("workbench.export.xml.usecdata", this.getUseCDATA());
		s.setProperty("workbench.export.xml.verbosexml", this.getUseVerboseXml());
		s.setProperty("workbench.export.xml.xmlversion", getXMLVersion());
	}

	public void restoreSettings()
	{
		Settings s = Settings.getInstance();
		this.setUseCDATA(s.getBoolProperty("workbench.export.xml.usecdata"));
		this.setUseVerboseXml(s.getBoolProperty("workbench.export.xml.verbosexml", true));
		String version = s.getProperty("workbench.export.xml.xmlversion", s.getDefaultXmlVersion());
		if (version.equals("1.0"))
		{
			xml10.setSelected(true);
		}
		else if (version.equals("1.1"))
		{
			xml11.setSelected(true);
		}
	}

	public String getXMLVersion()
	{
		if (xml11.isSelected())
		{
			return "1.1";
		}
		return "1.0";
	}

	public boolean getUseVerboseXml()
	{
		return this.verboseXmlCheckBox.isSelected();
	}

	public void setUseVerboseXml(boolean flag)
	{
		this.verboseXmlCheckBox.setSelected(flag);
	}

	public boolean getUseCDATA()
	{
		return useCdata.isSelected();
	}

	public void setUseCDATA(boolean flag)
	{
		useCdata.setSelected(flag);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    versionGroup = new javax.swing.ButtonGroup();
    useCdata = new javax.swing.JCheckBox();
    verboseXmlCheckBox = new javax.swing.JCheckBox();
    xml10 = new javax.swing.JRadioButton();
    xml11 = new javax.swing.JRadioButton();

    setLayout(new java.awt.GridBagLayout());

    useCdata.setText(ResourceMgr.getString("LblExportUseCDATA"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(useCdata, gridBagConstraints);

    verboseXmlCheckBox.setText(ResourceMgr.getString("LblExportVerboseXml"));
    verboseXmlCheckBox.setToolTipText(ResourceMgr.getDescription("LblExportVerboseXml"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    add(verboseXmlCheckBox, gridBagConstraints);

    versionGroup.add(xml10);
    xml10.setSelected(true);
    xml10.setText("XML 1.0");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(xml10, gridBagConstraints);

    versionGroup.add(xml11);
    xml11.setText("XML 1.1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weighty = 1.0;
    add(xml11, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox useCdata;
  private javax.swing.JCheckBox verboseXmlCheckBox;
  private javax.swing.ButtonGroup versionGroup;
  private javax.swing.JRadioButton xml10;
  private javax.swing.JRadioButton xml11;
  // End of variables declaration//GEN-END:variables

}
