/*
 * DriverEditorPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2010, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.profiles;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Driver;
import java.util.List;
import workbench.db.DbDriver;
import workbench.gui.components.ClassFinderGUI;
import workbench.gui.components.ExtensionFileFilter;
import workbench.gui.components.FlatButton;
import workbench.gui.components.TextComponentMouseListener;
import workbench.resource.ResourceMgr;
import workbench.util.ClassFinder;
import workbench.util.StringUtil;

/**
 *
 * @author  Thomas Kellerer
 */
public class DriverEditorPanel
	extends javax.swing.JPanel
	implements PropertyChangeListener
{
	private boolean ignoreChange;
	private DbDriver currentDriver;

	public DriverEditorPanel()
	{
		super();
		initComponents();
		String text = ResourceMgr.getDescription("LblDriverLibrary");
		text = text.replace("%path_sep%", StringUtil.getPathSeparator());
		lblLibrary.setToolTipText(text);
		libraryPath.setFileFilter(ExtensionFileFilter.getJarFileFilter());
		libraryPath.setLastDirProperty("workbench.drivers.lastlibdir");
		libraryPath.setTextfieldTooltip(text);
		libraryPath.setAllowMultiple(true);
		text = ResourceMgr.getDescription("SelectDriverLibrary");
		libraryPath.setButtonTooltip(text);
		libraryPath.addPropertyChangeListener("filename", this);
		libraryPath.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				selectClass();
			}
		});
	}

	public void propertyChange(PropertyChangeEvent evt)
	{
		if (ignoreChange) return;
		selectClass();
	}

	protected void selectClass()
	{
		ClassFinder finder = new ClassFinder(Driver.class);
		List<String> libs = DbDriver.splitLibraryList(libraryPath.getFilename());

		ClassFinderGUI gui = new ClassFinderGUI(finder, tfClassName, statusLabel);
		gui.setStatusBarKey("TxtSearchingDriver");
		gui.setWindowTitleKey("TxtSelectDriver");
		gui.setClassPath(libs);
		gui.startCheck();
	}

	public void setDriver(DbDriver aDriver)
	{
		try
		{
			ignoreChange = true;
			this.currentDriver = aDriver;
			this.tfName.setText(aDriver.getName());
			this.tfClassName.setText(aDriver.getDriverClass());
			this.libraryPath.setFilename(aDriver.getLibraryString());
			this.tfSampleUrl.setText(aDriver.getSampleUrl());
			this.detectDriverButton.setEnabled(StringUtil.isNonBlank(libraryPath.getFilename()));
		}
		finally
		{
			ignoreChange = false;
		}
	}

	void updateDriver()
	{
		this.currentDriver.setName(tfName.getText());
		this.currentDriver.setDriverClass(tfClassName.getText());
		this.currentDriver.setLibrary(libraryPath.getFilename());
		this.currentDriver.setSampleUrl(tfSampleUrl.getText());
	}

	public DbDriver getDriver()
	{
		this.updateDriver();
		return this.currentDriver;
	}

	public void reset()
	{
		this.currentDriver = null;
		this.tfName.setText("");
		this.tfClassName.setText("");
		this.libraryPath.setFilename("");
		this.tfSampleUrl.setText("");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    lblName = new javax.swing.JLabel();
    tfName = new javax.swing.JTextField();
    lblClassName = new javax.swing.JLabel();
    tfClassName = new javax.swing.JTextField();
    lblLibrary = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    lblSample = new javax.swing.JLabel();
    tfSampleUrl = new javax.swing.JTextField();
    libraryPath = new workbench.gui.components.WbFilePicker();
    statusLabel = new javax.swing.JLabel();
    detectDriverButton = new FlatButton();

    setFont(null);
    setLayout(new java.awt.GridBagLayout());

    lblName.setText(ResourceMgr.getString("LblDriverName")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 7);
    add(lblName, gridBagConstraints);

    tfName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    tfName.setMinimumSize(new java.awt.Dimension(50, 20));
    tfName.addMouseListener(new TextComponentMouseListener());
    tfName.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        DriverEditorPanel.this.focusLost(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(11, 3, 0, 3);
    add(tfName, gridBagConstraints);

    lblClassName.setText(ResourceMgr.getString("LblDriverClass")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 7);
    add(lblClassName, gridBagConstraints);

    tfClassName.setColumns(10);
    tfClassName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    tfClassName.addMouseListener(new TextComponentMouseListener());
    tfClassName.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        DriverEditorPanel.this.focusLost(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 3);
    add(tfClassName, gridBagConstraints);

    lblLibrary.setText(ResourceMgr.getString("LblDriverLibrary")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 7);
    add(lblLibrary, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    gridBagConstraints.weighty = 1.0;
    add(jPanel1, gridBagConstraints);

    lblSample.setText(ResourceMgr.getString("LblSampleUrl")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 7);
    add(lblSample, gridBagConstraints);

    tfSampleUrl.setColumns(10);
    tfSampleUrl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    tfSampleUrl.addMouseListener(new TextComponentMouseListener());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 3);
    add(tfSampleUrl, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 3);
    add(libraryPath, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(14, 10, 0, 7);
    add(statusLabel, gridBagConstraints);

    detectDriverButton.setIcon(ResourceMgr.getImage("magnifier.png"));
    detectDriverButton.setToolTipText(ResourceMgr.getString("MsgDetectDriver")); // NOI18N
    detectDriverButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
    detectDriverButton.setMaximumSize(new java.awt.Dimension(22, 22));
    detectDriverButton.setMinimumSize(new java.awt.Dimension(22, 22));
    detectDriverButton.setPreferredSize(new java.awt.Dimension(22, 22));
    detectDriverButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        detectDriverButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 4);
    add(detectDriverButton, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

	private void focusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_focusLost
	{//GEN-HEADEREND:event_focusLost
		this.updateDriver();
	}//GEN-LAST:event_focusLost

	private void detectDriverButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_detectDriverButtonActionPerformed
	{//GEN-HEADEREND:event_detectDriverButtonActionPerformed
		selectClass();
	}//GEN-LAST:event_detectDriverButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton detectDriverButton;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblClassName;
  private javax.swing.JLabel lblLibrary;
  private javax.swing.JLabel lblName;
  private javax.swing.JLabel lblSample;
  private workbench.gui.components.WbFilePicker libraryPath;
  private javax.swing.JLabel statusLabel;
  private javax.swing.JTextField tfClassName;
  private javax.swing.JTextField tfName;
  private javax.swing.JTextField tfSampleUrl;
  // End of variables declaration//GEN-END:variables
}
