/*
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2017, Thomas Kellerer.
 *
 * Licensed under a modified Apache License, Version 2.0
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://sql-workbench.net/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.net
 */

package workbench.gui.profiles;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import workbench.resource.IconMgr;


/**
 *
 * @author Thomas Kellerer
 */
class TemplateListEditor
	extends JPanel
	implements ListSelectionListener, ActionListener
{

	TemplateListEditor()
	{
		initComponents();
		templateList.getSelectionModel().addListSelectionListener(this);
		btnUp.addActionListener(this);
		btnDown.addActionListener(this);
		btnRemove.addActionListener(this);
	}

	public void setTemplates(List<ObjectFilterTemplate> templates)
	{
		DefaultListModel<ObjectFilterTemplate> model = new DefaultListModel<>();
		for (ObjectFilterTemplate templ : templates)
		{
			model.addElement(templ);
		}
		templateList.setModel(model);
		templateList.getSelectionModel().clearSelection();
		checkButtons();
	}

	public List<ObjectFilterTemplate> getTemplates()
	{
		int size = templateList.getModel().getSize();
		List<ObjectFilterTemplate> result = new ArrayList<>(size);
		for (int i=0; i < size; i++)
		{
      ObjectFilterTemplate template = (ObjectFilterTemplate)templateList.getModel().getElementAt(i);
			result.add(template);
		}
		return result;
	}

	@Override
	public void actionPerformed(ActionEvent e)
	{
		int[] indexes = templateList.getSelectedIndices();

		int selectedIndex = -1;
		if (indexes.length == 1)
		{
			selectedIndex = indexes[0];
		}

		DefaultListModel model = (DefaultListModel)templateList.getModel();
		int count = model.getSize();

		if (e.getSource() == btnRemove && indexes.length > 0)
		{
			removeSelected();
		}
		else if (e.getSource() == btnUp && selectedIndex > 0)
		{
			swap(selectedIndex, selectedIndex - 1);
		}
		else if (e.getSource() == btnDown && selectedIndex > -1 && selectedIndex < count - 1)
		{
			swap(selectedIndex, selectedIndex + 1);
		}
	}

	private void removeSelected()
	{
		int[] indexes = templateList.getSelectedIndices();
		if (indexes.length == 0) return;

		Arrays.sort(indexes);
		DefaultListModel model = (DefaultListModel)templateList.getModel();
		for (int i=indexes.length - 1; i >= 0; i --)
		{
			model.remove(indexes[i]);
		}
	}

	private void swap(int firstIndex, int secondIndex)
	{
		DefaultListModel model = (DefaultListModel)templateList.getModel();
		Object first = model.get(firstIndex);
		Object second = model.get(secondIndex);
		model.set(firstIndex, second);
		model.set(secondIndex, first);
		templateList.setSelectedIndex(secondIndex);
	}

	@Override
	public void valueChanged(ListSelectionEvent e)
	{
		checkButtons();
	}

	private void checkButtons()
	{
		int selectedIndex = templateList.getSelectedIndex();
		int count = templateList.getModel().getSize();
		btnRemove.setEnabled(selectedIndex > -1);
		btnUp.setEnabled(selectedIndex > 0);
		btnDown.setEnabled(selectedIndex > -1 && selectedIndex < count - 1);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane1 = new javax.swing.JScrollPane();
    templateList = new javax.swing.JList();
    btnRemove = new javax.swing.JButton();
    btnUp = new javax.swing.JButton();
    btnDown = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    templateList.setVerifyInputWhenFocusTarget(false);
    templateList.setVisibleRowCount(5);
    jScrollPane1.setViewportView(templateList);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridheight = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jScrollPane1, gridBagConstraints);

    btnRemove.setIcon(IconMgr.getInstance().getLabelIcon("delete"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
    add(btnRemove, gridBagConstraints);

    btnUp.setIcon(IconMgr.getInstance().getLabelIcon("Up"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(16, 8, 0, 0);
    add(btnUp, gridBagConstraints);

    btnDown.setIcon(IconMgr.getInstance().getLabelIcon("Down"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
    add(btnDown, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDown;
  private javax.swing.JButton btnRemove;
  private javax.swing.JButton btnUp;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList templateList;
  // End of variables declaration//GEN-END:variables
}
