/*
 * WbAboutDialog.java
 *
 * Created on 17. Juli 2002, 21:37
 */

package workbench.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.lang.Runtime;
import javax.swing.ActionMap;
import javax.swing.ComponentInputMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import workbench.gui.actions.EscAction;
import workbench.gui.components.TextComponentMouseListener;
import workbench.gui.components.UnderlineBorder;
import workbench.resource.ResourceMgr;
import workbench.util.BrowserLauncher;

/**
 *
 * @author  workbench@kellerer.org
 */
public class WbAboutDialog extends javax.swing.JDialog
	implements ActionListener
{
	private EscAction escAction;

	/** Creates new form WbAboutDialog */
	public WbAboutDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
		getRootPane().setDefaultButton(closeButton);
		InputMap im = new ComponentInputMap(this.getRootPane());
		ActionMap am = new ActionMap();
		escAction = new EscAction(this);
		im.put(escAction.getAccelerator(), escAction.getActionName());
		am.put(escAction.getActionName(), escAction);
		this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, im);
		this.getRootPane().setActionMap(am);
		this.contactInformation.addMouseListener(new TextComponentMouseListener());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		buttonPanel = new javax.swing.JPanel();
		closeButton = new javax.swing.JButton();
		contentPanel = new javax.swing.JPanel();
		logo = new javax.swing.JLabel();
		labelTitel = new javax.swing.JLabel();
		labelDesc = new javax.swing.JLabel();
		labelVersion = new javax.swing.JLabel();
		contactInformation = new javax.swing.JTextField();
		labelCopyright = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jdkVersion = new javax.swing.JLabel();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(ResourceMgr.getString("TxtAbout") + " " + ResourceMgr.TXT_PRODUCT_NAME);
		setName("AboutDialog");
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				closeDialog(evt);
			}
		});
		
		buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
		
		closeButton.setFont(null);
		closeButton.setText(ResourceMgr.getString("LabelClose"));
		closeButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				closeButtonActionPerformed(evt);
			}
		});
		
		buttonPanel.add(closeButton);
		
		getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
		
		contentPanel.setLayout(new java.awt.GridBagLayout());
		
		logo.setFont(null);
		logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workbench/resource/images/hitchguide.gif")));
		logo.setBorder(new javax.swing.border.EtchedBorder());
		logo.setIconTextGap(0);
		logo.setMaximumSize(new java.awt.Dimension(172, 128));
		logo.setMinimumSize(new java.awt.Dimension(172, 128));
		logo.setPreferredSize(new java.awt.Dimension(172, 128));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridheight = 6;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
		contentPanel.add(logo, gridBagConstraints);
		
		labelTitel.setFont(new java.awt.Font("Dialog", 1, 14));
		labelTitel.setText(ResourceMgr.TXT_PRODUCT_NAME);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 4);
		contentPanel.add(labelTitel, gridBagConstraints);
		
		labelDesc.setFont(null);
		labelDesc.setText(ResourceMgr.getString("TxtProductDescription"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 4);
		contentPanel.add(labelDesc, gridBagConstraints);
		
		labelVersion.setFont(null);
		labelVersion.setText(ResourceMgr.getString("TxtBuild"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 4);
		contentPanel.add(labelVersion, gridBagConstraints);
		
		contactInformation.setEditable(false);
		contactInformation.setText(ResourceMgr.getString("TxtContact"));
		contactInformation.setBorder(null);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 4);
		contentPanel.add(contactInformation, gridBagConstraints);
		
		labelCopyright.setFont(null);
		labelCopyright.setText(ResourceMgr.getString("TxtCopyright"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 4);
		contentPanel.add(labelCopyright, gridBagConstraints);
		
		jLabel1.setFont(new java.awt.Font("Dialog", 0, 11));
		jLabel1.setForeground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Label.disabledForeground"));
		jLabel1.setText("<html>Built with NetBeans (<u>www.netbeans.org</u>)</html>");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				jLabel1MouseClicked(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(4, 5, 0, 4);
		contentPanel.add(jLabel1, gridBagConstraints);
		
		jLabel2.setFont(new java.awt.Font("Dialog", 0, 11));
		jLabel2.setForeground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Label.disabledForeground"));
		jLabel2.setText("The editor is based on jEdit's 2.2.1 syntax highlighting package");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 4);
		contentPanel.add(jLabel2, gridBagConstraints);
		
		jdkVersion.setText(ResourceMgr.getString("TxtJavaVersion") + " " + System.getProperty("java.version"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 4);
		contentPanel.add(jdkVersion, gridBagConstraints);
		
		getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);
		
		pack();
	}//GEN-END:initComponents

	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel1MouseClicked
	{//GEN-HEADEREND:event_jLabel1MouseClicked
		try
		{
			if (evt.getClickCount() == 2) BrowserLauncher.openURL("http://www.netbeans.org");
		}
		catch (Exception e)
		{
		}
	}//GEN-LAST:event_jLabel1MouseClicked

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
	{//GEN-HEADEREND:event_closeButtonActionPerformed
		this.closeDialog(null);
	}//GEN-LAST:event_closeButtonActionPerformed

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt)
	{//GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	}//GEN-LAST:event_closeDialog

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		new WbAboutDialog(new javax.swing.JFrame(), true).show();
	}

	/** Invoked when an action occurs.
	 *
	 */
	public void actionPerformed(ActionEvent e)
	{
		if (e.getActionCommand().equals(escAction.getActionName()))
		{
			closeDialog(null);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel labelVersion;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel logo;
	private javax.swing.JLabel labelCopyright;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField contactInformation;
	private javax.swing.JLabel labelDesc;
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JButton closeButton;
	private javax.swing.JLabel labelTitel;
	private javax.swing.JLabel jdkVersion;
	private javax.swing.JPanel contentPanel;
	// End of variables declaration//GEN-END:variables

}
