/*
 * QuoteEscapeSelector
 *
 *  This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 *  Copyright 2002-2011, Thomas Kellerer
 *  No part of this code may be reused without the permission of the author
 *
 *  To contact the author please send an email to: support@sql-workbench.net
 */
package workbench.gui.dialogs;

import java.awt.event.ActionListener;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import workbench.resource.ResourceMgr;
import workbench.util.QuoteEscapeType;

/**
 *
 * @author Thomas Kellerer
 */
public class QuoteEscapeSelector
	extends JPanel
{

	public QuoteEscapeSelector()
	{
		initComponents();
		String[] items = new String[] {
			ResourceMgr.getString("TxtQuote.none"),
			ResourceMgr.getString("TxtQuote.escape"),
			ResourceMgr.getString("TxtQuote.duplicate")
		};
		ComboBoxModel model = new DefaultComboBoxModel(items);
		escapeSelect.setModel(model);
	}

	public void setEscapeType(QuoteEscapeType type)
	{
		switch (type)
		{
			case none:
				escapeSelect.setSelectedIndex(0);
				break;
			case escape:
				escapeSelect.setSelectedIndex(1);
				break;
			case duplicate:
				escapeSelect.setSelectedIndex(2);
				break;
		}
	}

	public QuoteEscapeType getEscapeType()
	{
		int index = escapeSelect.getSelectedIndex();
		if (index == 1) return QuoteEscapeType.escape;
		if (index == 2) return QuoteEscapeType.duplicate;
		return QuoteEscapeType.none;
	}

	public void addComboBoxActionListener(ActionListener l)
	{
		this.escapeSelect.addActionListener(l);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    escapeSelect = new javax.swing.JComboBox();

    jLabel1.setText(ResourceMgr.getString("LblQuoteEsc")); // NOI18N

    escapeSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addContainerGap(19, Short.MAX_VALUE))
      .addComponent(escapeSelect, 0, 86, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(escapeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox escapeSelect;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
