/*
 * TableDataSettings.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2016, Thomas Kellerer
 *
 * Licensed under a modified Apache License, Version 2.0
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at.
 *
 *     http://sql-workbench.net/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.dbobjects;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import workbench.resource.ResourceMgr;

import workbench.util.StringUtil;

/**
 *
 * @author Thomas Kellerer
 */
public class TableDataSettings
	extends javax.swing.JPanel
	implements ActionListener
{

	public TableDataSettings()
	{
		super();
		initComponents();
		this.checkBoxEnableWarning.addActionListener(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    GridBagConstraints gridBagConstraints;

    checkBoxEnableWarning = new JCheckBox();
    autoloadRowCount = new JCheckBox();
    autoloadData = new JCheckBox();
    thresholdLabel = new JLabel();
    textFieldThresholdValue = new JTextField();
    jPanel1 = new JPanel();

    setLayout(new GridBagLayout());

    checkBoxEnableWarning.setText(ResourceMgr.getString("LblEnableDataThresholdWarning")); // NOI18N
    checkBoxEnableWarning.setToolTipText(ResourceMgr.getString("d_LblEnableDataThresholdWarning")); // NOI18N
    checkBoxEnableWarning.setMargin(new Insets(0, 0, 0, 0));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    add(checkBoxEnableWarning, gridBagConstraints);

    autoloadRowCount.setText(ResourceMgr.getString("LblAutoLoadRowCount")); // NOI18N
    autoloadRowCount.setToolTipText(ResourceMgr.getString("d_LblAutoLoadRowCount")); // NOI18N
    autoloadRowCount.setMargin(new Insets(0, 0, 0, 0));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    gridBagConstraints.insets = new Insets(10, 0, 0, 0);
    add(autoloadRowCount, gridBagConstraints);

    autoloadData.setText(ResourceMgr.getString("LblAutoLoadTableData")); // NOI18N
    autoloadData.setToolTipText(ResourceMgr.getDescription("LblAutoLoadTableData"));
    autoloadData.setMargin(new Insets(0, 0, 0, 0));
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    gridBagConstraints.insets = new Insets(6, 0, 0, 0);
    add(autoloadData, gridBagConstraints);

    thresholdLabel.setText(ResourceMgr.getString("LblThresholdLevel")); // NOI18N
    thresholdLabel.setToolTipText(ResourceMgr.getString("d_LblThresholdLevel")); // NOI18N
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    add(thresholdLabel, gridBagConstraints);

    textFieldThresholdValue.setColumns(8);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(0, 4, 0, 9);
    add(textFieldThresholdValue, gridBagConstraints);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    add(jPanel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

	public int getThresholdValue()
	{
		if (this.checkBoxEnableWarning.isSelected())
		{
			return StringUtil.getIntValue(this.textFieldThresholdValue.getText(), -1);
		}
		else
		{
			return -1;
		}
	}

	public void setAutoloadRowCount(boolean flag) { this.autoloadRowCount.setSelected(flag); }
	public boolean getAutoloadRowCount() { return this.autoloadRowCount.isSelected(); }

	public void setAutoloadData(boolean flag) { this.autoloadData.setSelected(flag); }
	public boolean getAutoloadData() { return this.autoloadData.isSelected(); }

	public void setThresholdValue(int aValue)
	{
		this.checkBoxEnableWarning.setSelected(aValue > 0);
		this.textFieldThresholdValue.setEnabled(aValue > 0);
		this.thresholdLabel.setEnabled(aValue > 0);
		if (aValue <= 0)
		{
			this.textFieldThresholdValue.setText("");
		}
		else
		{
			this.textFieldThresholdValue.setText(Integer.toString(aValue));
		}
	}

	public void actionPerformed(java.awt.event.ActionEvent e)
	{
		if (e.getSource() == this.checkBoxEnableWarning)
		{
			this.textFieldThresholdValue.setEnabled(this.checkBoxEnableWarning.isSelected());
			this.thresholdLabel.setEnabled(this.checkBoxEnableWarning.isSelected());
		}
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JCheckBox autoloadData;
  private JCheckBox autoloadRowCount;
  private JCheckBox checkBoxEnableWarning;
  private JPanel jPanel1;
  private JTextField textFieldThresholdValue;
  private JLabel thresholdLabel;
  // End of variables declaration//GEN-END:variables

}
