/*
 * SelectTablePanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2017, Thomas Kellerer
 *
 * Licensed under a modified Apache License, Version 2.0
 * that restricts the use for certain governments.
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at.
 *
 *     http://sql-workbench.net/manual/license.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.components;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import workbench.interfaces.ValidatingComponent;
import workbench.resource.ResourceMgr;

/**
 *
 * @author Thomas Kellerer
 */
public class SelectTablePanel
	extends JPanel
	implements ValidatingComponent, ActionListener
{

	public SelectTablePanel(List<String> tablenames)
	{
		initComponents();
		tables.setModel(new DefaultComboBoxModel(tablenames.toArray(new String[tablenames.size()])));
	}

	@Override
	public boolean validateInput()
	{
		return tables.getSelectedItem() != null;
	}

	@Override
	public void componentDisplayed()
	{
	}

  @Override
  public void componentWillBeClosed()
  {
  }

	public String getSelectedTable()
	{
		return (String)tables.getSelectedItem();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    GridBagConstraints gridBagConstraints;

    jLabel1 = new JLabel();
    tables = new JComboBox();

    setLayout(new GridBagLayout());

    jLabel1.setText(ResourceMgr.getString("MsgEnterUpdateTable")); // NOI18N
    jLabel1.setVerticalAlignment(SwingConstants.TOP);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new Insets(5, 2, 0, 2);
    add(jLabel1, gridBagConstraints);

    tables.setModel(new DefaultComboBoxModel(new String[] { "person", "orders", "customer_type", "address", " " }));
    tables.addActionListener(this);
    gridBagConstraints = new GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new Insets(10, 2, 10, 2);
    add(tables, gridBagConstraints);
  }

  // Code for dispatching events from components to event handlers.

  public void actionPerformed(ActionEvent evt)
  {
    if (evt.getSource() == tables)
    {
      SelectTablePanel.this.tablesActionPerformed(evt);
    }
  }// </editor-fold>//GEN-END:initComponents

	private void tablesActionPerformed(ActionEvent evt)//GEN-FIRST:event_tablesActionPerformed
	{//GEN-HEADEREND:event_tablesActionPerformed

	}//GEN-LAST:event_tablesActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JLabel jLabel1;
  private JComboBox tables;
  // End of variables declaration//GEN-END:variables
}
