/*
 * WbColorPicker.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2008, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.components;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import javax.swing.BorderFactory;
import javax.swing.JColorChooser;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import workbench.resource.ResourceMgr;

/**
 *
 * @author support@sql-workbench.net
 */
public class WbColorPicker
	extends javax.swing.JPanel
	implements Serializable
{
	private Border sampleBorder;
	private ActionListener actionListener;
	
	public WbColorPicker()
	{
		this(false);
	}
	
	public WbColorPicker(boolean showReset)
	{
		initComponents();
		this.resetButton.setEnabled(showReset);
		this.resetButton.setVisible(showReset);
		if (showReset)
		{
			this.resetButton.setIcon(ResourceMgr.getImage("Delete"));
		}
		this.defaultLabel.setVisible(false);
		Dimension d = null;
		if (showReset)
		{
			d = resetButton.getPreferredSize();
		}
		else
		{
			d = selectColor.getPreferredSize();
		}
		d.height--;
		d.width--;
		this.samplePanel.setPreferredSize(d);
		this.sampleBorder = this.samplePanel.getBorder();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    samplePanel = new javax.swing.JPanel();
    infoPanel = new javax.swing.JPanel();
    resetButton = new FlatButton();
    selectColor = new FlatButton();
    defaultLabel = new javax.swing.JLabel();

    setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

    samplePanel.setBackground(new java.awt.Color(255, 255, 255));
    samplePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    samplePanel.setMaximumSize(new java.awt.Dimension(18, 18));
    samplePanel.setMinimumSize(new java.awt.Dimension(18, 18));
    samplePanel.setPreferredSize(new java.awt.Dimension(18, 18));
    samplePanel.setLayout(null);
    add(samplePanel);

    infoPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

    resetButton.setToolTipText(ResourceMgr.getDescription("LblResetColor"));
    resetButton.setMaximumSize(new java.awt.Dimension(22, 22));
    resetButton.setMinimumSize(new java.awt.Dimension(22, 22));
    resetButton.setPreferredSize(new java.awt.Dimension(22, 22));
    resetButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        resetButtonActionPerformed(evt);
      }
    });
    infoPanel.add(resetButton);

    selectColor.setText("...");
    selectColor.setMargin(new java.awt.Insets(0, 0, 0, 0));
    selectColor.setMaximumSize(new java.awt.Dimension(22, 22));
    selectColor.setMinimumSize(new java.awt.Dimension(22, 22));
    selectColor.setPreferredSize(new java.awt.Dimension(22, 22));
    selectColor.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        selectColorMouseClicked(evt);
      }
    });
    infoPanel.add(selectColor);

    defaultLabel.setText(ResourceMgr.getString("LblNone"));
    infoPanel.add(defaultLabel);

    add(infoPanel);
  }// </editor-fold>//GEN-END:initComponents

	private void selectColorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_selectColorMouseClicked
	{//GEN-HEADEREND:event_selectColorMouseClicked
		Color newColor = JColorChooser.showDialog(SwingUtilities.getWindowAncestor(this),
			ResourceMgr.getString("TxtSelectColor"), this.getSelectedColor());
		if (newColor != null)
		{
			this.setSelectedColor(newColor);
			fireColorChanged();
		}
	}//GEN-LAST:event_selectColorMouseClicked

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
		resetColor();
		fireColorChanged();
	}//GEN-LAST:event_resetButtonActionPerformed

	private void fireColorChanged()
	{
		if (this.actionListener != null)
		{
			this.actionListener.actionPerformed(new ActionEvent(this, 1,"color-changed"));
		}
	}

	public void setActionListener(ActionListener l)
	{
		this.actionListener = l;
	}
	
	private void resetColor()
	{
		this.resetButton.setEnabled(false);
		this.samplePanel.setBackground(this.getBackground());
		this.samplePanel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
		this.defaultLabel.setVisible(true);		
	}

	public void setSelectedColor(Color c)
	{
		if (c == null)
		{
			resetColor();
		}
		else
		{
			this.resetButton.setEnabled(true);
			defaultLabel.setVisible(false);
			samplePanel.setBackground(c);
			samplePanel.setBorder(sampleBorder);
		}
	}

	public Color getSelectedColor()
	{
		if (this.defaultLabel.isVisible())
		{
			return null;
		}
		else
		{
			return samplePanel.getBackground();
		}
	}
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel defaultLabel;
  private javax.swing.JPanel infoPanel;
  private javax.swing.JButton resetButton;
  private javax.swing.JPanel samplePanel;
  private javax.swing.JButton selectColor;
  // End of variables declaration//GEN-END:variables
}
