/*
 * DataEditOptionsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2007, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.settings;

import javax.swing.JPanel;
import workbench.gui.components.FlatButton;
import workbench.gui.components.WbCheckBoxLabel;
import workbench.resource.ResourceMgr;
import workbench.resource.Settings;
import workbench.util.FileDialogUtil;

/**
 * A panel to edit the options for data editing, such as the font to be 
 * used in the JTable, the PK Mapping file, colors used for required
 * fields and alternating row coloring.
 * 
 * @author  support@sql-workbench.net
 */
public class DataEditOptionsPanel
	extends JPanel
	implements java.awt.event.ActionListener, workbench.interfaces.Restoreable
{

	public DataEditOptionsPanel()
	{
		initComponents();
	}

	public void restoreSettings()
	{
		pkMapFile.setCaretPosition(0);
		previewDml.setSelected(Settings.getInstance().getPreviewDml());
		requiredFieldColor.setSelectedColor(Settings.getInstance().getRequiredFieldColor());
		highlightRequired.setSelected(Settings.getInstance().getHighlightRequiredFields());
		pkMapFile.setText(Settings.getInstance().getPKMappingFilename());
	}

	public void saveSettings()
	{
		Settings set = Settings.getInstance();
		set.setRequiredFieldColor(requiredFieldColor.getSelectedColor());
		set.setHighlightRequiredFields(this.highlightRequired.isSelected());
		set.setPreviewDml(this.previewDml.isSelected());
		set.setPKMappingFilename(pkMapFile.getText());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    pkMapFileLabel = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    pkMapFile = new javax.swing.JTextField();
    selectMapFile = new FlatButton();
    previewDmlLabel = new WbCheckBoxLabel();
    previewDml = new javax.swing.JCheckBox();
    requiredFieldLabel = new javax.swing.JLabel();
    requiredFieldColor = new workbench.gui.components.WbColorPicker();
    highlightRequiredLabel = new WbCheckBoxLabel();
    highlightRequired = new javax.swing.JCheckBox();
    dummyPanel = new javax.swing.JPanel();

    setLayout(new java.awt.GridBagLayout());

    pkMapFileLabel.setText(ResourceMgr.getString("LblPKMapFile"));
    pkMapFileLabel.setToolTipText(ResourceMgr.getDescription("LblPKMapFile"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
    add(pkMapFileLabel, gridBagConstraints);

    jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

    pkMapFile.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    pkMapFile.setMaximumSize(new java.awt.Dimension(2147483647, 22));
    pkMapFile.setMinimumSize(new java.awt.Dimension(6, 22));
    pkMapFile.setPreferredSize(new java.awt.Dimension(72, 22));
    jPanel3.add(pkMapFile, java.awt.BorderLayout.CENTER);

    selectMapFile.setText("...");
    selectMapFile.setMaximumSize(new java.awt.Dimension(22, 22));
    selectMapFile.setMinimumSize(new java.awt.Dimension(22, 22));
    selectMapFile.setPreferredSize(new java.awt.Dimension(22, 22));
    selectMapFile.addActionListener(this);
    jPanel3.add(selectMapFile, java.awt.BorderLayout.EAST);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 15);
    add(jPanel3, gridBagConstraints);

    previewDmlLabel.setLabelFor(previewDml);
    previewDmlLabel.setText(ResourceMgr.getString("LblPreviewDml"));
    previewDmlLabel.setToolTipText(ResourceMgr.getDescription("LblPreviewDml"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
    add(previewDmlLabel, gridBagConstraints);

    previewDml.setFont(null);
    previewDml.setText(" ");
    previewDml.setBorder(null);
    previewDml.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    previewDml.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    previewDml.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 9, 0, 11);
    add(previewDml, gridBagConstraints);

    requiredFieldLabel.setText(ResourceMgr.getString("LblReqFldColor"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
    add(requiredFieldLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(8, 4, 0, 25);
    add(requiredFieldColor, gridBagConstraints);

    highlightRequiredLabel.setLabelFor(highlightRequired);
    highlightRequiredLabel.setText(ResourceMgr.getString("LblHiliteRqd"));
    highlightRequiredLabel.setToolTipText(ResourceMgr.getDescription("LblHiliteRqd"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 0);
    add(highlightRequiredLabel, gridBagConstraints);

    highlightRequired.setFont(null);
    highlightRequired.setBorder(null);
    highlightRequired.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    highlightRequired.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    highlightRequired.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(9, 9, 0, 0);
    add(highlightRequired, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(dummyPanel, gridBagConstraints);
  }

  // Code for dispatching events from components to event handlers.

  public void actionPerformed(java.awt.event.ActionEvent evt) {
    if (evt.getSource() == selectMapFile) {
      DataEditOptionsPanel.this.selectMapFile(evt);
    }
  }// </editor-fold>//GEN-END:initComponents

	private void selectMapFile(java.awt.event.ActionEvent evt)//GEN-FIRST:event_selectMapFile
	{//GEN-HEADEREND:event_selectMapFile
		String fileName = FileDialogUtil.selectPkMapFile(this);
		if (fileName != null) pkMapFile.setText(fileName);
	}//GEN-LAST:event_selectMapFile


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel dummyPanel;
  private javax.swing.JCheckBox highlightRequired;
  private javax.swing.JLabel highlightRequiredLabel;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTextField pkMapFile;
  private javax.swing.JLabel pkMapFileLabel;
  private javax.swing.JCheckBox previewDml;
  private javax.swing.JLabel previewDmlLabel;
  private workbench.gui.components.WbColorPicker requiredFieldColor;
  private javax.swing.JLabel requiredFieldLabel;
  private javax.swing.JButton selectMapFile;
  // End of variables declaration//GEN-END:variables

}
