/*
 * FormatterOptionsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2006, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.settings;

import javax.swing.JPanel;
import workbench.gui.components.WbCheckBoxLabel;
import workbench.interfaces.Restoreable;
import workbench.resource.ResourceMgr;
import workbench.resource.Settings;
import workbench.util.StringUtil;

/**
 *
 * @author  support@sql-workbench.net
 */
public class FormatterOptionsPanel 
	extends JPanel
	implements Restoreable
{
	
	/** Creates new form FormatterOptionsPanel */
	public FormatterOptionsPanel()
	{
		initComponents();
		restoreSettings();
	}
	
	public void restoreSettings()
	{
		String genCase = Settings.getInstance().getGeneratedSqlTableCase();
		if ("lower".equals(genCase)) this.tableNameCase.setSelectedIndex(1);
		else if ("upper".equals(genCase)) this.tableNameCase.setSelectedIndex(2);
		else this.tableNameCase.setSelectedIndex(0);		
	}
	
	public void saveSettings()
	{
		Settings set = Settings.getInstance();
		set.setMaxNumInListElements(StringUtil.getIntValue(maxNumElements.getText(),-1));
		set.setMaxCharInListElements(StringUtil.getIntValue(maxCharElements.getText(),-1));
		set.setDoFormatUpdates(formatUpdates.isSelected());
		set.setDoFormatInserts(formatInserts.isSelected());
		set.setFormatInsertColsPerLine(StringUtil.getIntValue(insertColsPerLine.getText(),1));
		set.setFormatInsertColumnThreshold(StringUtil.getIntValue(insertThreshold.getText(),5));
		set.setFormatUpdateColumnThreshold(StringUtil.getIntValue(updateThreshold.getText(),5));
		set.setFormatterMaxSubselectLength(StringUtil.getIntValue(subselectMaxLength.getText(),60));
		set.setFormatterMaxColumnsInSelect(StringUtil.getIntValue(selectColumns.getText(),1));
		set.setIncludeOwnerInSqlExport(includeOwner.isSelected());
		set.setGeneratedSqlTableCase((String)tableNameCase.getSelectedItem());
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    internalFormatterPanel = new javax.swing.JPanel();
    formatUpdates = new javax.swing.JCheckBox();
    formatUpdatesLabel = new WbCheckBoxLabel();
    formatInsertsLabel = new WbCheckBoxLabel();
    formatInserts = new javax.swing.JCheckBox();
    insertColThresholdLbl = new javax.swing.JLabel();
    insertThreshold = new javax.swing.JTextField();
    updateThreshold = new javax.swing.JTextField();
    updateColThresholdLbl = new javax.swing.JLabel();
    ignoreIdentityLabel = new WbCheckBoxLabel();
    ignoreIdentity = new javax.swing.JCheckBox();
    jSeparator1 = new javax.swing.JSeparator();
    insertColsPerLine = new javax.swing.JTextField();
    colsPerLineLabel = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    includeOwner = new javax.swing.JCheckBox();
    includeOwnerLabel = new WbCheckBoxLabel();
    tableNameCaseLabel = new javax.swing.JLabel();
    tableNameCase = new javax.swing.JComboBox();
    editorFormatterPanel = new javax.swing.JPanel();
    subselectMaxLabel = new javax.swing.JLabel();
    subselectMaxLength = new javax.swing.JTextField();
    maxCharElementsLabel = new javax.swing.JLabel();
    maxCharElements = new javax.swing.JTextField();
    maxNumElementsLabel = new javax.swing.JLabel();
    maxNumElements = new javax.swing.JTextField();
    selectColumns = new javax.swing.JTextField();
    selectColumnsLabel = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    internalFormatterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Generated Statements"));
    internalFormatterPanel.setLayout(new java.awt.GridBagLayout());

    formatUpdates.setFont(null);
    formatUpdates.setSelected(Settings.getInstance().getDoFormatUpdates());
    formatUpdates.setText("");
    formatUpdates.setBorder(null);
    formatUpdates.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    formatUpdates.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    formatUpdates.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    internalFormatterPanel.add(formatUpdates, gridBagConstraints);

    formatUpdatesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    formatUpdatesLabel.setLabelFor(formatUpdates);
    formatUpdatesLabel.setText(ResourceMgr.getString("LblFmtUpd"));
    formatUpdatesLabel.setToolTipText(ResourceMgr.getDescription("LblFmtUpd"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(1, 12, 0, 0);
    internalFormatterPanel.add(formatUpdatesLabel, gridBagConstraints);

    formatInsertsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    formatInsertsLabel.setLabelFor(formatInserts);
    formatInsertsLabel.setText(ResourceMgr.getString("LblFmtIns"));
    formatInsertsLabel.setToolTipText(ResourceMgr.getDescription("LblFmtIns"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
    internalFormatterPanel.add(formatInsertsLabel, gridBagConstraints);

    formatInserts.setFont(null);
    formatInserts.setSelected(Settings.getInstance().getDoFormatInserts());
    formatInserts.setText("");
    formatInserts.setBorder(null);
    formatInserts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    formatInserts.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    formatInserts.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 11);
    internalFormatterPanel.add(formatInserts, gridBagConstraints);

    insertColThresholdLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    insertColThresholdLbl.setText(ResourceMgr.getString("LblInsThres"));
    insertColThresholdLbl.setToolTipText(ResourceMgr.getDescription("LblInsThres"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
    internalFormatterPanel.add(insertColThresholdLbl, gridBagConstraints);

    insertThreshold.setText(Integer.toString(Settings.getInstance().getFormatInsertColumnThreshold()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 15);
    internalFormatterPanel.add(insertThreshold, gridBagConstraints);

    updateThreshold.setText(Integer.toString(Settings.getInstance().getFormatUpdateColumnThreshold()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 15);
    internalFormatterPanel.add(updateThreshold, gridBagConstraints);

    updateColThresholdLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    updateColThresholdLbl.setText(ResourceMgr.getString("LblUpdThres"));
    updateColThresholdLbl.setToolTipText(ResourceMgr.getDescription("LblUpdThres"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 0);
    internalFormatterPanel.add(updateColThresholdLbl, gridBagConstraints);

    ignoreIdentityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    ignoreIdentityLabel.setLabelFor(ignoreIdentity);
    ignoreIdentityLabel.setText(ResourceMgr.getString("LblInsIgnoreId"));
    ignoreIdentityLabel.setToolTipText(ResourceMgr.getDescription("LblInsIgnoreId"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
    internalFormatterPanel.add(ignoreIdentityLabel, gridBagConstraints);

    ignoreIdentity.setFont(null);
    ignoreIdentity.setSelected(Settings.getInstance().getFormatInsertIgnoreIdentity());
    ignoreIdentity.setText("");
    ignoreIdentity.setBorder(null);
    ignoreIdentity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    ignoreIdentity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    ignoreIdentity.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 11);
    internalFormatterPanel.add(ignoreIdentity, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
    internalFormatterPanel.add(jSeparator1, gridBagConstraints);

    insertColsPerLine.setText(Integer.toString(Settings.getInstance().getFormatInsertColsPerLine()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 15);
    internalFormatterPanel.add(insertColsPerLine, gridBagConstraints);

    colsPerLineLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    colsPerLineLabel.setText(ResourceMgr.getString("LblInsColsPerLine"));
    colsPerLineLabel.setToolTipText(ResourceMgr.getDescription("LblInsColsPerLine"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(7, 18, 0, 0);
    internalFormatterPanel.add(colsPerLineLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
    internalFormatterPanel.add(jSeparator2, gridBagConstraints);

    includeOwner.setFont(null);
    includeOwner.setSelected(Settings.getInstance().getIncludeOwnerInSqlExport());
    includeOwner.setText("");
    includeOwner.setBorder(null);
    includeOwner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    includeOwner.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    includeOwner.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 11);
    internalFormatterPanel.add(includeOwner, gridBagConstraints);

    includeOwnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    includeOwnerLabel.setLabelFor(includeOwner);
    includeOwnerLabel.setText(ResourceMgr.getString("LblGenInclOwn"));
    includeOwnerLabel.setToolTipText(ResourceMgr.getDescription("LblGenInclOwn"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
    internalFormatterPanel.add(includeOwnerLabel, gridBagConstraints);

    tableNameCaseLabel.setLabelFor(tableNameCase);
    tableNameCaseLabel.setText(ResourceMgr.getString("LblGenTableNameCase"));
    tableNameCaseLabel.setToolTipText(ResourceMgr.getDescription("LblGenTableNameCase"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
    internalFormatterPanel.add(tableNameCaseLabel, gridBagConstraints);

    tableNameCase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "As is", "Lowercase", "Uppercase" }));
    tableNameCase.setToolTipText(ResourceMgr.getDescription("LblGenTableNameCase"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 15);
    internalFormatterPanel.add(tableNameCase, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 0.5;
    add(internalFormatterPanel, gridBagConstraints);

    editorFormatterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editor"));
    editorFormatterPanel.setLayout(new java.awt.GridBagLayout());

    subselectMaxLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    subselectMaxLabel.setText(ResourceMgr.getString("LblMaxSub"));
    subselectMaxLabel.setToolTipText(ResourceMgr.getDescription("LblMaxSub"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 12, 0, 0);
    editorFormatterPanel.add(subselectMaxLabel, gridBagConstraints);

    subselectMaxLength.setText(Integer.toString(Settings.getInstance().getFormatterMaxSubselectLength()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(1, 9, 0, 15);
    editorFormatterPanel.add(subselectMaxLength, gridBagConstraints);

    maxCharElementsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    maxCharElementsLabel.setText(ResourceMgr.getString("LblMaxCharEle"));
    maxCharElementsLabel.setToolTipText(ResourceMgr.getDescription("LblMaxCharEle"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
    editorFormatterPanel.add(maxCharElementsLabel, gridBagConstraints);

    maxCharElements.setText(Integer.toString(Settings.getInstance().getMaxCharInListElements()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 9, 0, 15);
    editorFormatterPanel.add(maxCharElements, gridBagConstraints);

    maxNumElementsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    maxNumElementsLabel.setText(ResourceMgr.getString("LblMaxNumEle"));
    maxNumElementsLabel.setToolTipText(ResourceMgr.getDescription("LblMaxNumEle"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
    editorFormatterPanel.add(maxNumElementsLabel, gridBagConstraints);

    maxNumElements.setText(Integer.toString(Settings.getInstance().getMaxNumInListElements()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 9, 0, 15);
    editorFormatterPanel.add(maxNumElements, gridBagConstraints);

    selectColumns.setText(Integer.toString(Settings.getInstance().getFormatterMaxColumnsInSelect()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 9, 0, 15);
    editorFormatterPanel.add(selectColumns, gridBagConstraints);

    selectColumnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    selectColumnsLabel.setText(ResourceMgr.getString("LblSqlFmtColNum"));
    selectColumnsLabel.setToolTipText(ResourceMgr.getDescription("LblSqlFmtColNum"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
    editorFormatterPanel.add(selectColumnsLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weighty = 0.5;
    add(editorFormatterPanel, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
	
	
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel colsPerLineLabel;
  private javax.swing.JPanel editorFormatterPanel;
  private javax.swing.JCheckBox formatInserts;
  private javax.swing.JLabel formatInsertsLabel;
  private javax.swing.JCheckBox formatUpdates;
  private javax.swing.JLabel formatUpdatesLabel;
  private javax.swing.JCheckBox ignoreIdentity;
  private javax.swing.JLabel ignoreIdentityLabel;
  private javax.swing.JCheckBox includeOwner;
  private javax.swing.JLabel includeOwnerLabel;
  private javax.swing.JLabel insertColThresholdLbl;
  private javax.swing.JTextField insertColsPerLine;
  private javax.swing.JTextField insertThreshold;
  private javax.swing.JPanel internalFormatterPanel;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JTextField maxCharElements;
  private javax.swing.JLabel maxCharElementsLabel;
  private javax.swing.JTextField maxNumElements;
  private javax.swing.JLabel maxNumElementsLabel;
  private javax.swing.JTextField selectColumns;
  private javax.swing.JLabel selectColumnsLabel;
  private javax.swing.JLabel subselectMaxLabel;
  private javax.swing.JTextField subselectMaxLength;
  private javax.swing.JComboBox tableNameCase;
  private javax.swing.JLabel tableNameCaseLabel;
  private javax.swing.JLabel updateColThresholdLbl;
  private javax.swing.JTextField updateThreshold;
  // End of variables declaration//GEN-END:variables
	
}
