/*
 * SettingsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2006, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.settings;

import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.WindowConstants;

import workbench.gui.WbSwingUtilities;
import workbench.gui.actions.EscAction;
import workbench.gui.components.NumberField;
import workbench.gui.components.WbButton;
import workbench.resource.ResourceMgr;
import workbench.resource.Settings;
import workbench.util.FileDialogUtil;
import workbench.util.StringUtil;

/**
 *
 * @author  sql.workbench@freenet.de
 */
public class SettingsPanel
	extends JPanel
	implements ActionListener
{
	private String escActionCommand;

	/** Creates new form SettingsPanel */
	public SettingsPanel()
	{
		initComponents();
		this.fontsComboBox.addItem(new FontListEntry(Settings.PROPERTY_DATA_FONT));
		this.fontsComboBox.addItem(new FontListEntry(Settings.PROPERTY_EDITOR_FONT));
		this.fontsComboBox.addItem(new FontListEntry(Settings.PROPERTY_STANDARD_FONT));
		this.fontsComboBox.addItem(new FontListEntry(Settings.PROPERTY_MSGLOG_FONT));
		this.fontsComboBox.addItem(new FontListEntry(Settings.PROPERTY_PRINTER_FONT));
		this.fontsComboBox.setSelectedIndex(0);
		this.enableDbmsOutput.addActionListener(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    mainTab = new javax.swing.JTabbedPane();
    generalPanel = new javax.swing.JPanel();
    dbExplorerLabel = new javax.swing.JLabel();
    showDbExplorer = new javax.swing.JCheckBox();
    useEncryptionLabel = new javax.swing.JLabel();
    useEncryption = new javax.swing.JCheckBox();
    dateFormatLabel = new javax.swing.JLabel();
    dateFormatTextField = new javax.swing.JTextField();
    altDelimLabel = new javax.swing.JLabel();
    altDelimitTextField = new javax.swing.JTextField();
    historySizeLabel = new javax.swing.JLabel();
    historySizeField = new NumberField();
    decimalLabel = new javax.swing.JLabel();
    decimalField = new javax.swing.JTextField();
    maxDigitsLabel = new javax.swing.JLabel();
    maxDigitsField = new NumberField();
    maxColSizeLabel = new javax.swing.JLabel();
    maxColSizeField = new NumberField();
    textDelimiterLabel = new javax.swing.JLabel();
    textDelimiterField = new javax.swing.JTextField();
    quoteCharLabel = new javax.swing.JLabel();
    quoteCharField = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    retrieveDbExplorer = new javax.swing.JCheckBox();
    retrieveDbExplorerLabel = new javax.swing.JLabel();
    previewDmlLabel = new javax.swing.JLabel();
    previewDml = new javax.swing.JCheckBox();
    enableDbmsOutputLabel = new javax.swing.JLabel();
    enableDbmsOutput = new javax.swing.JCheckBox();
    enableAnimatedIconLabel = new javax.swing.JLabel();
    enableAnimatedIcon = new javax.swing.JCheckBox();
    editorTabSizeLabel = new javax.swing.JLabel();
    defTableTypeField = new javax.swing.JTextField();
    consolidateLogLabel = new javax.swing.JLabel();
    consolidateLog = new javax.swing.JCheckBox();
    defaultBufferSize = new javax.swing.JTextField();
    bufferSizeLabel = new javax.swing.JLabel();
    autoAdvanceLabel = new javax.swing.JLabel();
    autoAdvance = new javax.swing.JCheckBox();
    defTableTypeLabel1 = new javax.swing.JLabel();
    tabSize = new javax.swing.JTextField();
    timestampFormatLabel = new javax.swing.JLabel();
    timestampFormatTextField = new javax.swing.JTextField();
    pkMapFileLabel = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    pkMapFile = new javax.swing.JTextField();
    selectMapFile = new javax.swing.JButton();
    fontPanel = new javax.swing.JPanel();
    fontsComboBox = new javax.swing.JComboBox();
    wbFontChooser1 = new workbench.gui.components.WbFontChooser();
    buttonPanel = new javax.swing.JPanel();
    okButton = new WbButton();
    cancelButton = new WbButton();

    setLayout(new java.awt.BorderLayout());

    mainTab.setFont(null);
    generalPanel.setLayout(new java.awt.GridBagLayout());

    dbExplorerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    dbExplorerLabel.setLabelFor(showDbExplorer);
    dbExplorerLabel.setText(ResourceMgr.getString("LabelDbExplorerCheckBox"));
    dbExplorerLabel.setToolTipText(ResourceMgr.getDescription("LabelDbExplorerCheckBox"));
    dbExplorerLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        dbExplorerLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
    generalPanel.add(dbExplorerLabel, gridBagConstraints);

    showDbExplorer.setFont(null);
    showDbExplorer.setSelected(Settings.getInstance().getShowDbExplorerInMainWindow());
    showDbExplorer.setText("");
    showDbExplorer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    showDbExplorer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    showDbExplorer.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(9, 7, 0, 11);
    generalPanel.add(showDbExplorer, gridBagConstraints);

    useEncryptionLabel.setLabelFor(useEncryption);
    useEncryptionLabel.setText(ResourceMgr.getString("LabelUseEncryption"));
    useEncryptionLabel.setToolTipText(ResourceMgr.getDescription("LabelUseEncryption"));
    useEncryptionLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        useEncryptionLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 0, 0);
    generalPanel.add(useEncryptionLabel, gridBagConstraints);

    useEncryption.setFont(null);
    useEncryption.setSelected(Settings.getInstance().getUseEncryption());
    useEncryption.setText("");
    useEncryption.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    useEncryption.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    useEncryption.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 0, 11);
    generalPanel.add(useEncryption, gridBagConstraints);

    dateFormatLabel.setFont(null);
    dateFormatLabel.setText(ResourceMgr.getString("LabelDateFormat"));
    dateFormatLabel.setToolTipText(ResourceMgr.getDescription("LabelDateFormat"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(dateFormatLabel, gridBagConstraints);

    dateFormatTextField.setFont(getFont());
    dateFormatTextField.setText(Settings.getInstance().getDefaultDateFormat());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(dateFormatTextField, gridBagConstraints);

    altDelimLabel.setText(ResourceMgr.getString("LabelAltDelimit"));
    altDelimLabel.setToolTipText(ResourceMgr.getDescription("LabelAltDelimit"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 11;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(altDelimLabel, gridBagConstraints);

    altDelimitTextField.setText(Settings.getInstance().getAlternateDelimiter());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 11;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(altDelimitTextField, gridBagConstraints);

    historySizeLabel.setText(ResourceMgr.getString("LabelHistorySize"));
    historySizeLabel.setToolTipText(ResourceMgr.getDescription("LabelHistorySize"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 12;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(historySizeLabel, gridBagConstraints);

    historySizeField.setText(Integer.toString(Settings.getInstance().getMaxHistorySize()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 12;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(historySizeField, gridBagConstraints);

    decimalLabel.setText(ResourceMgr.getString("LabelDecimalSymbol"));
    decimalLabel.setToolTipText(ResourceMgr.getDescription("LabelDecimalSymbol"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 13;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(decimalLabel, gridBagConstraints);

    decimalField.setText(Settings.getInstance().getDecimalSymbol());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 13;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(decimalField, gridBagConstraints);

    maxDigitsLabel.setText(ResourceMgr.getString("LabelMaxDigits"));
    maxDigitsLabel.setToolTipText(ResourceMgr.getDescription("LabelMaxDigits"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 14;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(maxDigitsLabel, gridBagConstraints);

    maxDigitsField.setText(Integer.toString(Settings.getInstance().getMaxFractionDigits()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 14;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(maxDigitsField, gridBagConstraints);

    maxColSizeLabel.setText(ResourceMgr.getString("LabelMaxColsize"));
    maxColSizeLabel.setToolTipText(ResourceMgr.getDescription("LabelMaxColsize"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 15;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(maxColSizeLabel, gridBagConstraints);

    maxColSizeField.setText(Integer.toString(Settings.getInstance().getMaxColumnWidth()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 15;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(maxColSizeField, gridBagConstraints);

    textDelimiterLabel.setText(ResourceMgr.getString("LabelFieldDelimiter"));
    textDelimiterLabel.setToolTipText(ResourceMgr.getDescription("LabelFieldDelimiter"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 16;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(textDelimiterLabel, gridBagConstraints);

    textDelimiterField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    textDelimiterField.setText(Settings.getInstance().getDefaultTextDelimiter(true));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 16;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(textDelimiterField, gridBagConstraints);

    quoteCharLabel.setText(ResourceMgr.getString("LabelQuoteChar"));
    quoteCharLabel.setToolTipText(ResourceMgr.getDescription("LabelQuoteChar"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 17;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(quoteCharLabel, gridBagConstraints);

    quoteCharField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    quoteCharField.setText(Settings.getInstance().getQuoteChar());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 17;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(quoteCharField, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 21;
    gridBagConstraints.weighty = 1.0;
    generalPanel.add(jPanel1, gridBagConstraints);

    retrieveDbExplorer.setFont(null);
    retrieveDbExplorer.setSelected(Settings.getInstance().getRetrieveDbExplorer());
    retrieveDbExplorer.setText("");
    retrieveDbExplorer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    retrieveDbExplorer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    retrieveDbExplorer.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 0, 11);
    generalPanel.add(retrieveDbExplorer, gridBagConstraints);

    retrieveDbExplorerLabel.setLabelFor(retrieveDbExplorer);
    retrieveDbExplorerLabel.setText(ResourceMgr.getString("LabelRetrieveDbExplorer"));
    retrieveDbExplorerLabel.setToolTipText(ResourceMgr.getDescription("LabelRetrieveDbExplorer"));
    retrieveDbExplorerLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        retrieveDbExplorerLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 0, 0);
    generalPanel.add(retrieveDbExplorerLabel, gridBagConstraints);

    previewDmlLabel.setLabelFor(retrieveDbExplorer);
    previewDmlLabel.setText(ResourceMgr.getString("LabelPreviewDml"));
    previewDmlLabel.setToolTipText(ResourceMgr.getDescription("LabelPreviewDml"));
    previewDmlLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        previewDmlLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 0, 0);
    generalPanel.add(previewDmlLabel, gridBagConstraints);

    previewDml.setFont(null);
    previewDml.setSelected(Settings.getInstance().getPreviewDml());
    previewDml.setText("");
    previewDml.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    previewDml.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    previewDml.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 0, 11);
    generalPanel.add(previewDml, gridBagConstraints);

    enableDbmsOutputLabel.setLabelFor(retrieveDbExplorer);
    enableDbmsOutputLabel.setText(ResourceMgr.getString("LabelEnableDbmsOutput"));
    enableDbmsOutputLabel.setToolTipText(ResourceMgr.getDescription("LabelEnableDbmsOutput"));
    enableDbmsOutputLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        enableDbmsOutputLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 0, 0);
    generalPanel.add(enableDbmsOutputLabel, gridBagConstraints);

    enableDbmsOutput.setFont(null);
    enableDbmsOutput.setSelected(Settings.getInstance().getEnableDbmsOutput());
    enableDbmsOutput.setText("");
    enableDbmsOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    enableDbmsOutput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    enableDbmsOutput.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 7, 0, 3);
    generalPanel.add(enableDbmsOutput, gridBagConstraints);

    enableAnimatedIconLabel.setLabelFor(enableAnimatedIcon);
    enableAnimatedIconLabel.setText(ResourceMgr.getString("LabelEnableAnimatedIcon"));
    enableAnimatedIconLabel.setToolTipText(ResourceMgr.getDescription("LabelEnableAnimatedIcon"));
    enableAnimatedIconLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        enableAnimatedIconLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 0);
    generalPanel.add(enableAnimatedIconLabel, gridBagConstraints);

    enableAnimatedIcon.setFont(null);
    enableAnimatedIcon.setSelected(Settings.getInstance().getUseAnimatedIcon());
    enableAnimatedIcon.setText("");
    enableAnimatedIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    enableAnimatedIcon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    enableAnimatedIcon.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 2, 11);
    generalPanel.add(enableAnimatedIcon, gridBagConstraints);

    editorTabSizeLabel.setText(ResourceMgr.getString("LabelTabWidth"));
    editorTabSizeLabel.setToolTipText(ResourceMgr.getDescription("LabelTabWidth"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 19;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(editorTabSizeLabel, gridBagConstraints);

    defTableTypeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    defTableTypeField.setText(Settings.getInstance().getProperty("workbench.dbexplorer.defTableType", null));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 18;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(defTableTypeField, gridBagConstraints);

    consolidateLogLabel.setLabelFor(consolidateLog);
    consolidateLogLabel.setText(ResourceMgr.getString("LabelConsolidateLog"));
    consolidateLogLabel.setToolTipText(ResourceMgr.getDescription("LabelConsolidateLog"));
    consolidateLogLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        consolidateLogLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 0);
    generalPanel.add(consolidateLogLabel, gridBagConstraints);

    consolidateLog.setFont(null);
    consolidateLog.setSelected(Settings.getInstance().getConsolidateLogMsg());
    consolidateLog.setText("");
    consolidateLog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    consolidateLog.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    consolidateLog.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 2, 11);
    generalPanel.add(consolidateLog, gridBagConstraints);

    defaultBufferSize.setText(Integer.toString(Settings.getInstance().getDbmsOutputDefaultBuffer()));
    defaultBufferSize.setMaximumSize(new java.awt.Dimension(2147483647, 21));
    defaultBufferSize.setMinimumSize(new java.awt.Dimension(100, 21));
    defaultBufferSize.setPreferredSize(new java.awt.Dimension(120, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 11);
    generalPanel.add(defaultBufferSize, gridBagConstraints);

    bufferSizeLabel.setText(ResourceMgr.getString("LabelDefaultBufferSize"));
    bufferSizeLabel.setToolTipText(ResourceMgr.getDescription("LabelDefaultBufferSize"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
    generalPanel.add(bufferSizeLabel, gridBagConstraints);

    autoAdvanceLabel.setLabelFor(autoAdvance);
    autoAdvanceLabel.setText(ResourceMgr.getString("LabelAutoAdvance"));
    autoAdvanceLabel.setToolTipText(ResourceMgr.getDescription("LabelAutoAdvance"));
    autoAdvanceLabel.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        autoAdvanceLabelMouseClicked(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 0);
    generalPanel.add(autoAdvanceLabel, gridBagConstraints);

    autoAdvance.setFont(null);
    autoAdvance.setSelected(Settings.getInstance().getAutoJumpNextStatement());
    autoAdvance.setText("");
    autoAdvance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    autoAdvance.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    autoAdvance.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 2, 11);
    generalPanel.add(autoAdvance, gridBagConstraints);

    defTableTypeLabel1.setText(ResourceMgr.getString("LabelDefTableType"));
    defTableTypeLabel1.setToolTipText(ResourceMgr.getDescription("LabelDefTableType"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 18;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(defTableTypeLabel1, gridBagConstraints);

    tabSize.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    tabSize.setText(Settings.getInstance().getProperty("workbench.editor.tabwidth", "2"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 19;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(tabSize, gridBagConstraints);

    timestampFormatLabel.setFont(null);
    timestampFormatLabel.setText(ResourceMgr.getString("LabelTimestampFormat"));
    timestampFormatLabel.setToolTipText(ResourceMgr.getDescription("LabelTimestampFormat"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(timestampFormatLabel, gridBagConstraints);

    timestampFormatTextField.setFont(getFont());
    timestampFormatTextField.setText(Settings.getInstance().getDefaultTimestampFormat());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(timestampFormatTextField, gridBagConstraints);

    pkMapFileLabel.setText(ResourceMgr.getString("LabelPKMapFile"));
    pkMapFileLabel.setToolTipText(ResourceMgr.getDescription("LabelPKMapFile"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 20;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
    generalPanel.add(pkMapFileLabel, gridBagConstraints);

    jPanel2.setLayout(new java.awt.BorderLayout());

    pkMapFile.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    pkMapFile.setText(Settings.getInstance().getPKMappingFilename());
    jPanel2.add(pkMapFile, java.awt.BorderLayout.CENTER);

    selectMapFile.setText("...");
    selectMapFile.setMaximumSize(new java.awt.Dimension(26, 22));
    selectMapFile.setMinimumSize(new java.awt.Dimension(26, 22));
    selectMapFile.setPreferredSize(new java.awt.Dimension(26, 22));
    selectMapFile.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        selectMapFile(evt);
      }
    });

    jPanel2.add(selectMapFile, java.awt.BorderLayout.EAST);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 20;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 11);
    generalPanel.add(jPanel2, gridBagConstraints);

    mainTab.addTab(ResourceMgr.getString("LabelSettingsGeneral"), generalPanel);

    fontPanel.setLayout(new java.awt.GridBagLayout());

    fontsComboBox.addItemListener(new java.awt.event.ItemListener()
    {
      public void itemStateChanged(java.awt.event.ItemEvent evt)
      {
        fontsComboBoxItemStateChanged(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 2);
    fontPanel.add(fontsComboBox, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    fontPanel.add(wbFontChooser1, gridBagConstraints);

    mainTab.addTab(ResourceMgr.getString("LabelSettingsFontsTab"), fontPanel);

    add(mainTab, java.awt.BorderLayout.CENTER);

    buttonPanel.setLayout(new java.awt.GridBagLayout());

    okButton.setText(ResourceMgr.getString("LabelOK"));
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 10);
    buttonPanel.add(okButton, gridBagConstraints);

    cancelButton.setText(ResourceMgr.getString("LabelCancel"));
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 4);
    buttonPanel.add(cancelButton, gridBagConstraints);

    add(buttonPanel, java.awt.BorderLayout.SOUTH);

  }// </editor-fold>//GEN-END:initComponents

	private void selectMapFile(java.awt.event.ActionEvent evt)//GEN-FIRST:event_selectMapFile
	{//GEN-HEADEREND:event_selectMapFile
		String fileName = FileDialogUtil.selectPkMapFile(this);
		if (fileName != null) pkMapFile.setText(fileName);
	}//GEN-LAST:event_selectMapFile

	private void fontsComboBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_fontsComboBoxItemStateChanged
	{//GEN-HEADEREND:event_fontsComboBoxItemStateChanged
		FontListEntry entry;
		if (evt.getStateChange() == ItemEvent.DESELECTED)
		{
			entry = (FontListEntry)evt.getItem();
			entry.currentFont = this.wbFontChooser1.getSelectedFont();
		}
		else if (evt.getStateChange() == ItemEvent.SELECTED)
		{
			entry = (FontListEntry)evt.getItem();
			this.wbFontChooser1.setSelectedFont(entry.currentFont);
			this.fontsComboBox.setToolTipText(entry.tooltip);
		}
	}//GEN-LAST:event_fontsComboBoxItemStateChanged

	private void autoAdvanceLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_autoAdvanceLabelMouseClicked
	{//GEN-HEADEREND:event_autoAdvanceLabelMouseClicked
		this.autoAdvance.setSelected(!this.autoAdvance.isSelected());
	}//GEN-LAST:event_autoAdvanceLabelMouseClicked

  private void previewDmlLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_previewDmlLabelMouseClicked
  {//GEN-HEADEREND:event_previewDmlLabelMouseClicked
	this.previewDml.setSelected(!this.previewDml.isSelected());
  }//GEN-LAST:event_previewDmlLabelMouseClicked

  private void consolidateLogLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_consolidateLogLabelMouseClicked
  {//GEN-HEADEREND:event_consolidateLogLabelMouseClicked
	this.consolidateLog.setSelected(!this.consolidateLog.isSelected());
  }//GEN-LAST:event_consolidateLogLabelMouseClicked

	private void enableAnimatedIconLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_enableAnimatedIconLabelMouseClicked
	{//GEN-HEADEREND:event_enableAnimatedIconLabelMouseClicked
		this.enableAnimatedIcon.setSelected(!this.enableAnimatedIcon.isSelected());
	}//GEN-LAST:event_enableAnimatedIconLabelMouseClicked

	private void enableDbmsOutputLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_enableDbmsOutputLabelMouseClicked
	{//GEN-HEADEREND:event_enableDbmsOutputLabelMouseClicked
		this.enableDbmsOutput.setSelected(!this.enableDbmsOutput.isSelected());
		this.defaultBufferSize.setEnabled(this.enableDbmsOutput.isSelected());
	}//GEN-LAST:event_enableDbmsOutputLabelMouseClicked

	private void retrieveDbExplorerLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_retrieveDbExplorerLabelMouseClicked
	{//GEN-HEADEREND:event_retrieveDbExplorerLabelMouseClicked
		this.retrieveDbExplorer.setSelected(!this.retrieveDbExplorer.isSelected());
	}//GEN-LAST:event_retrieveDbExplorerLabelMouseClicked

	private void useEncryptionLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_useEncryptionLabelMouseClicked
	{//GEN-HEADEREND:event_useEncryptionLabelMouseClicked
		this.useEncryption.setSelected(!this.useEncryption.isSelected());
	}//GEN-LAST:event_useEncryptionLabelMouseClicked

	private void dbExplorerLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_dbExplorerLabelMouseClicked
	{//GEN-HEADEREND:event_dbExplorerLabelMouseClicked
		this.showDbExplorer.setSelected(!this.showDbExplorer.isSelected());
	}//GEN-LAST:event_dbExplorerLabelMouseClicked

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
	{//GEN-HEADEREND:event_cancelButtonActionPerformed
		this.closeWindow();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
	{//GEN-HEADEREND:event_okButtonActionPerformed
		if (this.saveSettings()) this.closeWindow();
	}//GEN-LAST:event_okButtonActionPerformed

	private boolean saveSettings()
	{
		Settings set = Settings.getInstance();
		set.setShowDbExplorerInMainWindow(this.showDbExplorer.isSelected());
		set.setAlternateDelimiter(this.altDelimitTextField.getText());
		set.setDefaultDateFormat(this.dateFormatTextField.getText());
		set.setDefaultTimestampFormat(this.timestampFormatTextField.getText());
		set.setDecimalSymbol(this.decimalField.getText());
		set.setUseEncryption(this.useEncryption.isSelected());
		set.setRetrieveDbExplorer(retrieveDbExplorer.isSelected());
		set.setPreviewDml(this.previewDml.isSelected());
		set.setUseAnimatedIcon(this.enableAnimatedIcon.isSelected());

		set.setMaxHistorySize(((NumberField)this.historySizeField).getValue());
		set.setMaxColumnWidth(((NumberField)this.maxColSizeField).getValue());
		set.setMaxFractionDigits(((NumberField)this.maxDigitsField).getValue());
		set.setDefaultTextDelimiter(this.textDelimiterField.getText());
		set.setQuoteChar(this.quoteCharField.getText().trim());
		set.setEnableDbmsOutput(this.enableDbmsOutput.isSelected());
		set.setProperty("workbench.dbexplorer.defTableType", this.defTableTypeField.getText());
		set.setConsolidateLogMsg(this.consolidateLog.isSelected());
    set.setEnableDbmsOutput(this.enableDbmsOutput.isSelected());
    set.setDbmsOutputDefaultBuffer(StringUtil.getIntValue(this.defaultBufferSize.getText(), -1));
		set.setAutoJumpNextStatement(this.autoAdvance.isSelected());
		set.setEditorTabWidth(StringUtil.getIntValue(this.tabSize.getText(), 2));
		set.setPKMappingFilename(pkMapFile.getText());
		FontListEntry entry = (FontListEntry)this.fontsComboBox.getSelectedItem();
		entry.currentFont = this.wbFontChooser1.getSelectedFont();

		for (int i=0; i < this.fontsComboBox.getItemCount(); i++)
		{
			entry = (FontListEntry)this.fontsComboBox.getItemAt(i);
			set.setFont(entry.key, entry.currentFont);
		}
		return true;
	}

	public void showSettingsDialog(JFrame aReference)
	{
		//this.parent = aReference;
		this.dialog = new JDialog(aReference, true);
		this.dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		this.dialog.setTitle(ResourceMgr.getString("TxtSettingsDialogTitle"));
		this.dialog.getContentPane().add(this);
		this.dialog.pack();
		int width = Settings.getInstance().getWindowWidth(this.getClass().getName());
		if (width > 0)
		{
			this.dialog.setSize(width, this.dialog.getHeight());
		}

		this.dialog.getRootPane().setDefaultButton(this.okButton);

		JRootPane root = dialog.getRootPane();
		InputMap im = root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
		ActionMap am = root.getActionMap();
		EscAction esc = new EscAction(this);
		escActionCommand = esc.getActionName();
		im.put(esc.getAccelerator(), esc.getActionName());
		am.put(esc.getActionName(), esc);

		WbSwingUtilities.center(this.dialog, aReference);
		this.dialog.setVisible(true);
	}

	private void closeWindow()
	{
		Settings.getInstance().setWindowSize(this.getClass().getName(), this.dialog.getWidth(), this.dialog.getHeight());
		this.dialog.setVisible(false);
		this.dialog.dispose();
	}

	public void actionPerformed(java.awt.event.ActionEvent e)
	{
		if (e.getSource() == this.enableDbmsOutput)
		{
			this.defaultBufferSize.setEnabled(this.enableDbmsOutput.isSelected());
		}
		else if (e.getActionCommand().equals(escActionCommand))
		{
			this.closeWindow();
		}
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel altDelimLabel;
  private javax.swing.JTextField altDelimitTextField;
  private javax.swing.JCheckBox autoAdvance;
  private javax.swing.JLabel autoAdvanceLabel;
  private javax.swing.JLabel bufferSizeLabel;
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JCheckBox consolidateLog;
  private javax.swing.JLabel consolidateLogLabel;
  private javax.swing.JLabel dateFormatLabel;
  private javax.swing.JTextField dateFormatTextField;
  private javax.swing.JLabel dbExplorerLabel;
  private javax.swing.JTextField decimalField;
  private javax.swing.JLabel decimalLabel;
  private javax.swing.JTextField defTableTypeField;
  private javax.swing.JLabel defTableTypeLabel1;
  private javax.swing.JTextField defaultBufferSize;
  private javax.swing.JLabel editorTabSizeLabel;
  private javax.swing.JCheckBox enableAnimatedIcon;
  private javax.swing.JLabel enableAnimatedIconLabel;
  private javax.swing.JCheckBox enableDbmsOutput;
  private javax.swing.JLabel enableDbmsOutputLabel;
  private javax.swing.JPanel fontPanel;
  private javax.swing.JComboBox fontsComboBox;
  private javax.swing.JPanel generalPanel;
  private javax.swing.JTextField historySizeField;
  private javax.swing.JLabel historySizeLabel;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTabbedPane mainTab;
  private javax.swing.JTextField maxColSizeField;
  private javax.swing.JLabel maxColSizeLabel;
  private javax.swing.JTextField maxDigitsField;
  private javax.swing.JLabel maxDigitsLabel;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField pkMapFile;
  private javax.swing.JLabel pkMapFileLabel;
  private javax.swing.JCheckBox previewDml;
  private javax.swing.JLabel previewDmlLabel;
  private javax.swing.JTextField quoteCharField;
  private javax.swing.JLabel quoteCharLabel;
  private javax.swing.JCheckBox retrieveDbExplorer;
  private javax.swing.JLabel retrieveDbExplorerLabel;
  private javax.swing.JButton selectMapFile;
  private javax.swing.JCheckBox showDbExplorer;
  private javax.swing.JTextField tabSize;
  private javax.swing.JTextField textDelimiterField;
  private javax.swing.JLabel textDelimiterLabel;
  private javax.swing.JLabel timestampFormatLabel;
  private javax.swing.JTextField timestampFormatTextField;
  private javax.swing.JCheckBox useEncryption;
  private javax.swing.JLabel useEncryptionLabel;
  private workbench.gui.components.WbFontChooser wbFontChooser1;
  // End of variables declaration//GEN-END:variables

	private JDialog dialog;

	private class FontListEntry
	{
		String displayName;
		String key;
		Font currentFont;
		String tooltip;
		public FontListEntry(String aKey)
		{
			this.displayName = ResourceMgr.getString("Label"+ aKey + "Font");
			this.key = aKey;
			this.currentFont = Settings.getInstance().getFont(aKey);
			this.tooltip = ResourceMgr.getDescription("Label"+ aKey + "Font");
		}
		public String toString() { return this.displayName; }
	}


}
