/*
 * WindowTitleOptionsPanel.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2007, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.settings;

import workbench.gui.components.WbCheckBoxLabel;
import workbench.gui.components.WbTraversalPolicy;
import workbench.gui.components.WbTraversalPolicy;
import workbench.resource.ResourceMgr;
import workbench.resource.Settings;

/**
 *
 * @author support@sql-workbench.net
 */
public class WindowTitleOptionsPanel 
	extends javax.swing.JPanel
	implements workbench.interfaces.Restoreable
{
	
	public WindowTitleOptionsPanel()
	{
		initComponents();
		// It is important to add these in the correct order
		// which is defined by the numeric values from Settings.SHOW_NO_FILENAME
		// SHOW_FILENAME and SHOW_FULL_PATH
		this.windowTitleComboBox.addItem(ResourceMgr.getString("TxtShowNone"));
		this.windowTitleComboBox.addItem(ResourceMgr.getString("TxtShowName"));
		this.windowTitleComboBox.addItem(ResourceMgr.getString("TxtShowPath"));
		
		WbTraversalPolicy policy = new WbTraversalPolicy();
		policy.addComponent(showProfileGroup);
		policy.addComponent(showWorkspace);
		policy.addComponent(windowTitleComboBox);
		
		policy.setDefaultComponent(showProfileGroup);

		this.setFocusCycleRoot(true);
		this.setFocusTraversalPolicy(policy);	
		this.restoreSettings();
	}

  public void restoreSettings()
  {
		int type = Settings.getInstance().getShowFilenameInWindowTitle();
		if (type >= Settings.SHOW_NO_FILENAME && type <= Settings.SHOW_FULL_PATH)
		{
			this.windowTitleComboBox.setSelectedIndex(type);
		}
		this.showProfileGroup.setSelected(Settings.getInstance().getShowProfileGroupInWindowTitle());
		this.showWorkspace.setSelected(Settings.getInstance().getShowWorkspaceInWindowTitle());
  }

  public void saveSettings()
  {
		Settings set = Settings.getInstance();
		set.setShowFilenameInWindowTitle(this.windowTitleComboBox.getSelectedIndex());
		set.setShowProfileGroupInWindowTitle(showProfileGroup.isSelected());
		set.setShowWorkspaceInWindowTitle(showWorkspace.isSelected());
  }
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    showProfileGroupLabel = new WbCheckBoxLabel();
    showProfileGroup = new javax.swing.JCheckBox();
    showWorkspace = new javax.swing.JCheckBox();
    showWorkspaceLabel = new WbCheckBoxLabel();
    windowTitleLabel = new javax.swing.JLabel();
    windowTitleComboBox = new javax.swing.JComboBox();
    jPanel1 = new javax.swing.JPanel();

    setLayout(new java.awt.GridBagLayout());

    showProfileGroupLabel.setLabelFor(showProfileGroup);
    showProfileGroupLabel.setText(ResourceMgr.getString("LblShowProfileGroup"));
    showProfileGroupLabel.setToolTipText(ResourceMgr.getDescription("LblShowProfileGroup"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 12, 2, 0);
    add(showProfileGroupLabel, gridBagConstraints);

    showProfileGroup.setText("");
    showProfileGroup.setBorder(null);
    showProfileGroup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    showProfileGroup.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    showProfileGroup.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 10, 2, 11);
    add(showProfileGroup, gridBagConstraints);

    showWorkspace.setText("");
    showWorkspace.setBorder(null);
    showWorkspace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    showWorkspace.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    showWorkspace.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 11);
    add(showWorkspace, gridBagConstraints);

    showWorkspaceLabel.setLabelFor(showWorkspace);
    showWorkspaceLabel.setText(ResourceMgr.getString("LblShowWorkspace")
    );
    showWorkspaceLabel.setToolTipText(ResourceMgr.getDescription("LblShowWorkspace"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 12, 0, 0);
    add(showWorkspaceLabel, gridBagConstraints);

    windowTitleLabel.setLabelFor(windowTitleComboBox);
    windowTitleLabel.setText(ResourceMgr.getString("LblShowEditorInfo"));
    windowTitleLabel.setToolTipText(ResourceMgr.getDescription("LblShowEditorInfo"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(1, 12, 0, 0);
    add(windowTitleLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 15);
    add(windowTitleComboBox, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.weighty = 1.0;
    add(jPanel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JCheckBox showProfileGroup;
  private javax.swing.JLabel showProfileGroupLabel;
  private javax.swing.JCheckBox showWorkspace;
  private javax.swing.JLabel showWorkspaceLabel;
  private javax.swing.JComboBox windowTitleComboBox;
  private javax.swing.JLabel windowTitleLabel;
  // End of variables declaration//GEN-END:variables
	
}
