/*
 * WorkspaceOptions.java
 *
 * This file is part of SQL Workbench/J, http://www.sql-workbench.net
 *
 * Copyright 2002-2012, Thomas Kellerer
 * No part of this code maybe reused without the permission of the author
 *
 * To contact the author please send an email to: support@sql-workbench.net
 *
 */
package workbench.gui.settings;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import workbench.gui.components.WbFilePicker;
import workbench.interfaces.Restoreable;
import workbench.resource.ResourceMgr;
import workbench.resource.Settings;
import workbench.util.StringUtil;

/**
 *
 * @author  Thomas Kellerer
 */
public class WorkspaceOptions
	extends JPanel
	implements Restoreable, ActionListener
{
	public WorkspaceOptions()
	{
		super();
		initComponents();
		String[] types = new String[] {
			ResourceMgr.getString("LblFileWksplink"),
			ResourceMgr.getString("LblFileWkspcontent"),
			ResourceMgr.getString("LblFileWkspnone")
		};
		fileHandling.setModel(new DefaultComboBoxModel(types));
	}

	@Override
	public void restoreSettings()
	{
		autoSaveWorkspace.setSelected(Settings.getInstance().getAutoSaveWorkspace());
		createBackup.setSelected(Settings.getInstance().getCreateWorkspaceBackup());
		backupCount.setEnabled(createBackup.isSelected());
		backupCount.setText(Integer.toString(Settings.getInstance().getMaxWorkspaceBackup()));
		backupDirPicker.setFilename(Settings.getInstance().getWorkspaceBackupDir());
		backupSettingsFile.setSelected(Settings.getInstance().makeBackups());
		ExternalFileHandling handling = Settings.getInstance().getFilesInWorkspaceHandling();
		switch (handling)
		{
			case link:
				fileHandling.setSelectedIndex(0);
				break;
			case content:
				fileHandling.setSelectedIndex(1);
				break;
			case none:
				fileHandling.setSelectedIndex(2);
				break;
			default:
				fileHandling.setSelectedIndex(0);
		}
	}

	@Override
	public void saveSettings()
	{
		Settings set = Settings.getInstance();

		// General settings
		set.setAutoSaveWorkspace(autoSaveWorkspace.isSelected());
		set.setCreateWorkspaceBackup(createBackup.isSelected());
		int index = fileHandling.getSelectedIndex();
		switch (index)
		{
			case 0:
				set.setFilesInWorkspaceHandling(ExternalFileHandling.link);
				break;
			case 1:
				set.setFilesInWorkspaceHandling(ExternalFileHandling.content);
				break;
			case 2:
				set.setFilesInWorkspaceHandling(ExternalFileHandling.none);
				break;
			default:
				set.setFilesInWorkspaceHandling(ExternalFileHandling.link);
		}
		int value = StringUtil.getIntValue(backupCount.getText(), -1);
		if (value > -1)
		{
			set.setMaxWorkspaceBackup(value);
		}
		set.setWorkspaceBackupDir(backupDirPicker.getFilename());
		set.setMakeBackups(backupSettingsFile.isSelected());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    autoSaveWorkspace = new javax.swing.JCheckBox();
    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    fileHandling = new javax.swing.JComboBox();
    jPanel2 = new javax.swing.JPanel();
    createBackup = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();
    backupCount = new javax.swing.JTextField();
    backupSettingsFile = new javax.swing.JCheckBox();
    jLabel2 = new javax.swing.JLabel();
    backupDirPicker = new workbench.gui.components.WbFilePicker();

    setLayout(new java.awt.GridBagLayout());

    autoSaveWorkspace.setText(ResourceMgr.getString("LblAutoSaveWksp")); // NOI18N
    autoSaveWorkspace.setToolTipText(ResourceMgr.getString("d_LblAutoSaveWksp")); // NOI18N
    autoSaveWorkspace.setBorder(null);
    autoSaveWorkspace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    autoSaveWorkspace.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    autoSaveWorkspace.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 12, 3, 0);
    add(autoSaveWorkspace, gridBagConstraints);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel3.setText(ResourceMgr.getString("LblRememberFileWksp")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 3, 0, 0);
    jPanel1.add(jLabel3, gridBagConstraints);

    fileHandling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
    jPanel1.add(fileHandling, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
    add(jPanel1, gridBagConstraints);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(ResourceMgr.getString("LblWkspVersioning"))); // NOI18N
    jPanel2.setLayout(new java.awt.GridBagLayout());

    createBackup.setText(ResourceMgr.getString("LblBckWksp")); // NOI18N
    createBackup.setToolTipText(ResourceMgr.getString("d_LblBckWksp")); // NOI18N
    createBackup.setBorder(null);
    createBackup.addActionListener(this);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
    jPanel2.add(createBackup, gridBagConstraints);

    jLabel1.setLabelFor(backupCount);
    jLabel1.setText(ResourceMgr.getString("LblMaxWkspBck")); // NOI18N
    jLabel1.setToolTipText(ResourceMgr.getString("d_LblMaxWkspBck")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(1, 32, 1, 2);
    jPanel2.add(jLabel1, gridBagConstraints);

    backupCount.setColumns(3);
    backupCount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
    backupCount.setToolTipText(ResourceMgr.getString("d_LblMaxWkspBck")); // NOI18N
    backupCount.setMinimumSize(new java.awt.Dimension(30, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 1, 0);
    jPanel2.add(backupCount, gridBagConstraints);

    backupSettingsFile.setText(ResourceMgr.getString("LblAutoSaveSettings")); // NOI18N
    backupSettingsFile.setToolTipText(ResourceMgr.getString("d_LblAutoSaveSettings")); // NOI18N
    backupSettingsFile.setBorder(null);
    backupSettingsFile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    backupSettingsFile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    backupSettingsFile.setIconTextGap(5);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(7, 32, 3, 0);
    jPanel2.add(backupSettingsFile, gridBagConstraints);

    jLabel2.setText(ResourceMgr.getString("LblBckDir")); // NOI18N
    jLabel2.setToolTipText(ResourceMgr.getString("d_LblBckDir")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 32, 4, 0);
    jPanel2.add(jLabel2, gridBagConstraints);

    backupDirPicker.setToolTipText(ResourceMgr.getString("d_LblBckDir")); // NOI18N
    backupDirPicker.setSelectDirectoryOnly(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 5, 11);
    jPanel2.add(backupDirPicker, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(7, 9, 0, 9);
    add(jPanel2, gridBagConstraints);
  }

  // Code for dispatching events from components to event handlers.

  public void actionPerformed(java.awt.event.ActionEvent evt)
  {
    if (evt.getSource() == createBackup)
    {
      WorkspaceOptions.this.createBackupActionPerformed(evt);
    }
  }// </editor-fold>//GEN-END:initComponents

	private void createBackupActionPerformed(ActionEvent evt)//GEN-FIRST:event_createBackupActionPerformed
	{//GEN-HEADEREND:event_createBackupActionPerformed
		backupCount.setEnabled(createBackup.isSelected());
		backupSettingsFile.setEnabled(createBackup.isSelected());
	}//GEN-LAST:event_createBackupActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox autoSaveWorkspace;
  private javax.swing.JTextField backupCount;
  private workbench.gui.components.WbFilePicker backupDirPicker;
  private javax.swing.JCheckBox backupSettingsFile;
  private javax.swing.JCheckBox createBackup;
  private javax.swing.JComboBox fileHandling;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables

}
